Repository googleapis/sdk-platform-java, pull requests merged in 2021-11, with the labels that each got.

#862 fix: Use parent type instead of child_type in method doc sample
  src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java
  src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposer.java
  src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
  src/main/java/com/google/api/generator/gapic/protoparser/ResourceReferenceParser.java
  src/main/java/com/google/api/generator/gapic/utils/ResourceReferenceUtils.java
  src/test/java/com/google/api/generator/gapic/composer/common/TestProtoLoader.java
  src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java
  src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceClientClassComposerTest.java
  src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/MessagingClient.golden
  src/test/java/com/google/api/generator/gapic/protoparser/ResourceReferenceParserTest.java
  src/test/java/com/google/api/generator/gapic/testdata/BUILD.bazel
  src/test/java/com/google/api/generator/gapic/testdata/messaging.proto
  src/test/java/com/google/api/generator/gapic/utils/BUILD.bazel
  src/test/java/com/google/api/generator/gapic/utils/ResourceReferenceUtilsTest.java
  test/integration/goldens/README.md
  test/integration/goldens/logging/com/google/cloud/logging/v2/ConfigClient.java
  test/integration/goldens/logging/com/google/cloud/logging/v2/ConfigClientTest.java
  test/integration/goldens/logging/com/google/cloud/logging/v2/LoggingClient.java
  test/integration/goldens/logging/com/google/cloud/logging/v2/MetricsClient.java
  test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/SchemaServiceClient.java
Labels: cla: yes, samples

#872 fix: revert gradle version used for the bazel-generated assembly packages
  rules_java_gapic/resources/gradle/gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#873 Update gax-java to latest 2.7.0
  WORKSPACE
Labels: automerge, cla: yes

#870 chore: refactor convoluted logic
  src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java
Labels: cla: yes

#871 chore: do minor code simplification
  rules_java_gapic/java_gapic.bzl
  src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientTestClassComposer.java
  src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubClassComposer.java
  src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java
Labels: automerge, cla: yes
