Repository googleapis/sdk-platform-java, pull requests merged in 2023-10, with the labels that each got.

#2061 build: use errorprone's GuardedBy rather than javax's
  gax-java/gax-httpjson/BUILD.bazel
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCallImpl.java
  gax-java/gax/BUILD.bazel
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ServerStreamingAttemptCallable.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/Watchdog.java
Labels: size: xs

#2072 deps: Bumping java-shared-config to 1.5.8
  gapic-generator-java-pom-parent/pom.xml
  gax-java/gax-bom/pom.xml
  java-shared-dependencies/first-party-dependencies/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
  java-shared-dependencies/upper-bound-check/pom.xml
  showcase/pom.xml
Labels: size: s

#2070 feat: more logging for ChannelPool shutdown
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/ChannelPool.java
Labels: automerge, size: xs

#2088 chore: Enabling Dependency Dashboard for renovate-bot
  renovate.json
Labels: size: xs

#2084 chore: include/exclude certain protos when generating libraries
  library_generation/generate_library.sh
Labels: size: m

#2093 chore: Fixing renovate config
  renovate.json
Labels: size: m

#2106 chore: modify showcase test coverage
  .github/workflows/sonar.yaml
  showcase/grpc-gapic-showcase-v1beta1/pom.xml
  showcase/proto-gapic-showcase-v1beta1/pom.xml
Labels: size: s

#2108 chore: Debugging renovate-bot failure.
  renovate.json
Labels: automerge, size: s

#2121 feat: add gapic options as inputs to `generate_library.sh`
  library_generation/README.md
  library_generation/generate_library.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/proto_path_list.txt
  library_generation/test/test_utilities.sh
  library_generation/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: m

#2120 feat: replace graal-sdk version declaration with properties placeholder
  gax-java/pom.xml
Labels: size: xs

#2105 feat: log DirectPath misconfiguration
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: size: m

#2185 fix: Make sure outstanding RPCs count in ChannelPool can not go negative
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/ChannelPool.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/ChannelPoolTest.java
Labels: automerge, size: m

#2039 chore: Fix flaky testCancelIsTraced test
  gax-java/gax/src/test/java/com/google/api/gax/retrying/ScheduledRetryingExecutorTest.java
Labels: size: s

#2197 chore: Update release-please configuration
  .github/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: size: s

#2209 deps: update graal-sdk to 22.3.3 in bazel dependencies file
  gax-java/dependencies.properties
Labels: size: xs

#2212 chore: update graalvm container images to 22.3.3
  .kokoro/presubmit/graalvm-native-17-downstream.cfg
  .kokoro/presubmit/graalvm-native-downstream.cfg
  renovate.json
Labels: size: s

#1951 feat: `generate_library.sh` with postprocessing
  .github/workflows/verify_library_generation.yaml
  library_generation/README.md
  library_generation/generate_library.sh
  library_generation/postprocess_library.sh
  library_generation/test/compare_poms.py
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/proto_path_list.txt
  library_generation/test/resources/test-monorepo/.github/.OwlBot.lock.yaml
  library_generation/test/resources/test-monorepo/test-service/.repo-metadata.json
  library_generation/test/test_utilities.sh
  library_generation/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: l, hermetic-build
