Repository googleapis/sdk-platform-java, pull requests merged in 2023-07, with the labels that each got.

#1726 fix: [gapic-generator-java] handle response and metadata type ambiguity in LRO parsing
  gapic-generator-java/src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/TypeParserTest.java
  gapic-generator-java/src/test/proto/collisions.proto
Labels: size: l

#1829 build(deps): Bump grpc-java version to 1.55.3
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
Labels: size: xs

#1830 chore: Bump gapic-showcase version to 0.28.2
  .github/workflows/ci.yaml
  .github/workflows/sonar.yaml
  .kokoro/presubmit/downstream-build.sh
  WORKSPACE
  showcase/README.md
  showcase/gapic-showcase/pom.xml
Labels: size: s

#1832 build(deps): Bump guava version to 32.1.1-jre
  gapic-generator-java-pom-parent/pom.xml
  gapic-generator-java/pom.xml
  gax-java/dependencies.properties
  java-common-protos/pom.xml
  rules_java_gapic/resources/gradle/client_grpc.gradle.tmpl
  rules_java_gapic/resources/gradle/client_grpcrest.gradle.tmpl
  rules_java_gapic/resources/gradle/client_rest.gradle.tmpl
Labels: size: s

#1834 chore: Add j2obc-annotations to shared-dependencies
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#1835 ci: fix showcase-clirr check on release PRs
  .github/workflows/ci.yaml
Labels: size: xs

#1833 ci: showcase native check
  .github/workflows/ci.yaml
  .kokoro/presubmit/common.cfg
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITGdch.java
  showcase/gapic-showcase/src/test/resources/META-INF/native-image/resource-config.json
Labels: size: m

#1818 fix: Use bindings for resolving multi pattern resources
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/compliance/getiampolicy/AsyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/compliance/getiampolicy/SyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/compliance/setiampolicy/AsyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/compliance/setiampolicy/SyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/compliance/testiampermissions/AsyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/compliance/testiampermissions/SyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/echo/getiampolicy/AsyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/echo/getiampolicy/SyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/echo/setiampolicy/AsyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/echo/setiampolicy/SyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/echo/testiampermissions/AsyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/echo/testiampermissions/SyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/identity/getiampolicy/AsyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/identity/getiampolicy/SyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/identity/setiampolicy/AsyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/identity/setiampolicy/SyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/identity/testiampermissions/AsyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/identity/testiampermissions/SyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/messaging/getiampolicy/AsyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/messaging/getiampolicy/SyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/messaging/setiampolicy/AsyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/messaging/setiampolicy/SyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/messaging/testiampermissions/AsyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/messaging/testiampermissions/SyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/sequenceservice/getiampolicy/AsyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/sequenceservice/getiampolicy/SyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/sequenceservice/setiampolicy/AsyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/sequenceservice/setiampolicy/SyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/sequenceservice/testiampermissions/AsyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/sequenceservice/testiampermissions/SyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/testing/getiampolicy/AsyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/testing/getiampolicy/SyncGetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/testing/setiampolicy/AsyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/testing/setiampolicy/SyncSetIamPolicy.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/testing/testiampermissions/AsyncTestIamPermissions.java
  showcase/gapic-showcase/samples/snippets/generated/src/main/java/com/google/showcase/v1beta1/testing/testiampermissions/SyncTestIamPermissions.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/ComplianceClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/IdentityClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/MessagingClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/SequenceServiceClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/TestingClient.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/ComplianceClientHttpJsonTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/ComplianceClientTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/EchoClientHttpJsonTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/EchoClientTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/IdentityClientHttpJsonTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/IdentityClientTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/MessagingClientHttpJsonTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/MessagingClientTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/SequenceServiceClientHttpJsonTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/SequenceServiceClientTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/TestingClientHttpJsonTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/TestingClientTest.java
  showcase/pom.xml
Labels: size: l

#1856 chore: enable renovate bot
  renovate.json
Labels: automerge, size: xs

#1857 chore: update DEVELOPMENT.md for sdk-platform-java rename
  gapic-generator-java/DEVELOPMENT.md
Labels: size: xs

#1810 chore: http-client version deduplication
  gapic-generator-java-bom/pom.xml
  gapic-generator-java-pom-parent/pom.xml
  gax-java/pom.xml
  java-shared-dependencies/first-party-dependencies/pom.xml
Labels: size: s

#1860 chore: resource name class composer cleanup
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposer.java
Labels: size: s

#1861 chore: include src/main/resources in gapic output
  rules_java_gapic/java_gapic.bzl
  rules_java_gapic/java_gapic_pkg.bzl
Labels: size: s

#1865 chore: remove gson version duplication
  java-shared-dependencies/first-party-dependencies/pom.xml
Labels: size: xs

#1867 build(deps): Bump grpc version to 1.56.1
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
Labels: size: xs

#1870 build(deps): Bump java-shared-configs version to 1.5.7
  gapic-generator-java-pom-parent/pom.xml
  gax-java/gax-bom/pom.xml
  java-shared-dependencies/first-party-dependencies/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
  java-shared-dependencies/upper-bound-check/pom.xml
Labels: automerge, size: s

#1859 deps: auto-value version 1.10.2
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
Labels: size: xs

#1877 ci: configure the 2.22.x protected branch
  .github/workflows/ci.yaml
  .github/workflows/shared_dependencies.yaml
  .github/workflows/sonar.yaml
Labels: size: m

#1866 chore: gax-java now uses third-party-dependencies' management
  gax-java/pom.xml
Labels: size: s

#1881 Revert "chore: gax-java now uses third-party-dependencies' management"
  gax-java/pom.xml
Labels: size: s

#1885 test: Add unit tests for percent encoding for all special characters.
  gax-java/gax/src/main/java/com/google/api/gax/rpc/RequestUrlParamsEncoder.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/RequestUrlParamsEncoderTest.java
Labels: size: s
