Repository googleapis/sdk-platform-java, pull requests merged in 2023-09, with the labels that each got.

#1948 chore: add unit tests for `utilities.sh`
  .github/workflows/verify_library_generation.yaml
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/alloydb/alloydb_v1.yaml
  library_generation/test/resources/firestore/firestore_v1.yaml
  library_generation/test/resources/monitoring/QueryServiceGrpc_copy.java
  library_generation/test/resources/monitoring/monitoring.yaml
  library_generation/test/resources/monitoring/monitoring_gapic.yaml
  library_generation/test/resources/monitoring/monitoring_grpc_service_config.json
  library_generation/test/resources/pubsub/pubsub_v1.yaml
  library_generation/utilities.sh
Labels: size: xl

#1892 fix: remove -H:-RunReachabilityHandlersConcurrently
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/nativeimage/ProtobufMessageFeature.java
  gax-java/gax-grpc/src/main/resources/META-INF/native-image/com.google.api/gax-grpc/native-image.properties
Labels: size: m

#1961 chore: shell code format
  .github/workflows/verify_library_generation.yaml
  library_generation/gapic-generator-java-wrapper
  library_generation/generate_library.sh
  library_generation/generate_library_integration_test.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/alloydb/alloydb_v1.yaml
  library_generation/test/resources/firestore/firestore_v1.yaml
  library_generation/test/resources/gapic_options/QueryServiceGrpc_copy.java
  library_generation/test/resources/gapic_options/example.yaml
  library_generation/test/resources/gapic_options/example_gapic.yaml
  library_generation/test/resources/gapic_options/example_grpc_service_config.json
  library_generation/test/resources/monitoring/monitoring.yaml
  library_generation/test/resources/monitoring/monitoring_gapic.yaml
  library_generation/test/resources/monitoring/monitoring_grpc_service_config.json
  library_generation/test/resources/pubsub/pubsub_v1.yaml
  library_generation/test/resources/search_additional_protos/common_resources/search_additional_protos_common_resources_test.yaml
  library_generation/test/resources/search_additional_protos/iam/search_additional_protos_iam_test.yaml
  library_generation/test/resources/search_additional_protos/iam_location/search_additional_protos_iam_location_test.yaml
  library_generation/test/resources/search_additional_protos/location/search_additional_protos_location_test.yaml
  library_generation/utilities.sh
Labels: size: xl

#1963 feat: Adding vendor and vendor information in header
  gax-java/gax/src/main/java/com/google/api/gax/core/GaxProperties.java
  gax-java/gax/src/test/java/com/google/api/gax/core/GaxPropertiesTest.java
Labels: size: m

#1968 chore: add a lint for shell script
  .github/workflows/verify_library_generation.yaml
  library_generation/test/generate_library_unit_tests.sh
Labels: size: s

#1935 feat: generate showcase without post-processing
  library_generation/README.md
  library_generation/generate_library.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/misc/TESTBUILD.bazel
  library_generation/test/resources/misc/TESTWORKSPACE
  library_generation/test/resources/misc/testversions.txt
  library_generation/utilities.sh
  showcase/gapic-showcase/pom.xml
  showcase/grpc-gapic-showcase-v1beta1/pom.xml
  showcase/pom.xml
  showcase/proto-gapic-showcase-v1beta1/pom.xml
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/compliance.proto
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/echo.proto
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/identity.proto
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/messaging.proto
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/sequence.proto
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/testing.proto
  showcase/scripts/BUILD.bazel
  showcase/scripts/generate_components.sh
  showcase/scripts/generate_showcase.sh
  showcase/scripts/showcase_utilities.sh
  showcase/scripts/update.sh
  showcase/scripts/verify.sh
Labels: size: l

#1964 chore: add unit tests for `generate_library.sh`
  .github/workflows/verify_library_generation.yaml
  library_generation/README.md
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/test_utilities.sh
  library_generation/utilities.sh
Labels: size: l

#1988 feat: hermetic build OS detection
  .github/workflows/verify_library_generation.yaml
  library_generation/generate_library.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/utilities.sh
Labels: size: s

#1979 fix: skip generating `grpc-*` directory if transport is `rest`
  library_generation/generate_library.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/misc/BUILD_grpc.bazel
  library_generation/test/resources/misc/BUILD_grpc_rest.bazel
  library_generation/test/resources/misc/BUILD_include_samples_empty.bazel
  library_generation/test/resources/misc/BUILD_include_samples_false.bazel
  library_generation/test/resources/misc/BUILD_include_samples_true.bazel
  library_generation/test/resources/misc/BUILD_rest.bazel
  library_generation/test/resources/misc/BUILD_rest_numeric_enums_empty.bazel
  library_generation/test/resources/misc/BUILD_rest_numeric_enums_false.bazel
  library_generation/test/resources/misc/BUILD_rest_numeric_enums_true.bazel
  library_generation/test/resources/misc/TESTBUILD.bazel
  library_generation/utilities.sh
Labels: size: l

#1987 feat: hermetic build scripts to use a single output/generation folder
  .gitignore
  library_generation/README.md
  library_generation/generate_library.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/utilities.sh
  showcase/scripts/generate_showcase.sh
  showcase/scripts/showcase_utilities.sh
  showcase/scripts/verify.sh
Labels: size: m

#1991 chore: Change `generate_library_integration_test.sh `to test on multiple libraries in `googleapis-gen`
  .github/workflows/verify_library_generation.yaml
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/resources/proto_path_list.txt
  library_generation/utilities.sh
Labels: size: m

#1998 chore: Copy grafeas from googleapis
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/resources/proto_path_list.txt
Labels: size: xs

#2001 test: fix concurrency issue in testThrottlingBlocking
  gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: automerge, size: s

#2002 fix: showcase update goal fix
  showcase/scripts/generate_components.sh
Labels: automerge, size: xs

#2004 feat: search gapic additional protos in `BUILD.bazel`
  library_generation/README.md
  library_generation/generate_library.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/search_additional_protos/BUILD_common_resources.bazel
  library_generation/test/resources/search_additional_protos/BUILD_iam_locations.bazel
  library_generation/test/resources/search_additional_protos/BUILD_iam_policy.bazel
  library_generation/test/resources/search_additional_protos/BUILD_locations.bazel
  library_generation/test/resources/search_additional_protos/common_resources/search_additional_protos_common_resources_test.yaml
  library_generation/test/resources/search_additional_protos/iam/search_additional_protos_iam_test.yaml
  library_generation/test/resources/search_additional_protos/iam_location/search_additional_protos_iam_location_test.yaml
  library_generation/test/resources/search_additional_protos/location/search_additional_protos_location_test.yaml
  library_generation/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: m

#2013 chore: refactor test utilities
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/test_utilities.sh
  library_generation/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: l

#2015 feat: filter out `*gapic.legacy.yaml` when parsing `java_gapic_opts`
  library_generation/test/resources/gapic_options/example_gapic.legacy.yaml
  library_generation/test/resources/gapic_options/example_gapic_legacy.yaml
  library_generation/utilities.sh
Labels: size: xs

#2016 ci: move downstream check to independent yaml file
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: size: m

#1989 build(deps): bump grpc version to 1.58.0 and protobuf to 3.24.0
  .github/workflows/ci.yaml
  .kokoro/presubmit/downstream-compatibility.sh
  api-common-java/pom.xml
  gapic-generator-java-pom-parent/pom.xml
  gapic-generator-java/pom.xml
  gax-java/dependencies.properties
  gax-java/gax-grpc/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
  java-shared-dependencies/upper-bound-check/pom.xml
  showcase/gapic-showcase/src/main/resources/META-INF/native-image/com.google.showcase.v1beta1/reflect-config.json
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ComplianceGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/IdentityGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/MessagingGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/SequenceServiceGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/TestingGrpc.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/BlockRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/Blurb.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ComplianceData.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ComplianceDataChild.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/CreateBlurbRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/CreateRoomRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/CreateSequenceRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/CreateSessionRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/CreateStreamingSequenceRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/CreateUserRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EnumResponse.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ExpandRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/RepeatRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/RepeatResponse.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/Room.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/SearchBlurbsMetadata.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/Sequence.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/SequenceReport.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/StreamBlurbsRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/StreamBlurbsResponse.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/StreamingSequence.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/StreamingSequenceReport.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/Test.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/TestRun.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/UpdateBlurbRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/UpdateRoomRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/UpdateUserRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/User.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/VerifyTestRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/VerifyTestResponse.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/WaitMetadata.java
  test/integration/goldens/apigeeconnect/src/META-INF/native-image/com.google.cloud.apigeeconnect.v1/reflect-config.json
  test/integration/goldens/asset/src/META-INF/native-image/com.google.cloud.asset.v1/reflect-config.json
  test/integration/goldens/bigtable/src/META-INF/native-image/com.google.cloud.bigtable.data.v2/reflect-config.json
  test/integration/goldens/compute/src/META-INF/native-image/com.google.cloud.compute.v1small/reflect-config.json
  test/integration/goldens/credentials/src/META-INF/native-image/com.google.cloud.iam.credentials.v1/reflect-config.json
  test/integration/goldens/iam/src/META-INF/native-image/com.google.iam.v1/reflect-config.json
  test/integration/goldens/kms/src/META-INF/native-image/com.google.cloud.kms.v1/reflect-config.json
  test/integration/goldens/library/src/META-INF/native-image/com.google.cloud.example.library.v1/reflect-config.json
  test/integration/goldens/logging/src/META-INF/native-image/com.google.cloud.logging.v2/reflect-config.json
  test/integration/goldens/pubsub/src/META-INF/native-image/com.google.cloud.pubsub.v1/reflect-config.json
  test/integration/goldens/redis/src/META-INF/native-image/com.google.cloud.redis.v1beta1/reflect-config.json
  test/integration/goldens/storage/src/META-INF/native-image/com.google.storage.v2/reflect-config.json
Labels: size: l

#2003 docs: add repo-metadata.json files for modules we publish Cloud RAD d…
  api-common-java/.repo-metadata.json
  gax-java/.repo-metadata.json
  java-common-protos/.repo-metadata.json
  java-core/.repo-metadata.json
  java-iam/.repo-metadata.json
Labels: size: s

#2020 deps: update protobuf dependencies to v3.24.3
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
Labels: size: xs

#2019 chore: restore monorepo check to be pinned at latest version
  .kokoro/presubmit/downstream-compatibility.sh
Labels: size: s

#2022 docs: add release level to gax metadata
  gax-java/.repo-metadata.json
Labels: size: xs

#2023 fix(hermetic-build): obtain gapic-generator-java locally on release branch
  library_generation/README.md
  library_generation/test/generate_library_unit_tests.sh
  library_generation/utilities.sh
Labels: size: m

#2029 chore: revert exclusion for `j2objc-annotations`
  gapic-generator-java/pom.xml
  gax-java/dependencies.properties
  gax-java/gax-httpjson/pom.xml
  java-core/google-cloud-core/pom.xml
Labels: size: s

#2033 fix: Add Geo common protos to Bazel test dependencies.
  rules_java_gapic/java_gapic.bzl
Labels: automerge, size: xs

#2006 chore: Fix flaky testCancelOuterFutureAfterStart test
  gax-java/gax/src/test/java/com/google/api/gax/retrying/ScheduledRetryingExecutorTest.java
Labels: size: s

#2040 chore: download the parent pom to output folder
  library_generation/utilities.sh
Labels: size: s

#2046 feat: generate proto-only library
  library_generation/README.md
  library_generation/generate_library.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/resources/proto_path_list.txt
  library_generation/test/test_utilities.sh
  library_generation/utilities.sh
Labels: size: m
