Repository googleapis/sdk-platform-java, pull requests merged in 2023-05, with the labels that each got.

#1657 feat: remove directpath enable env
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
Labels: size: s

#1643 feat: add an option to enable DirectPath xDS
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: automerge, size: m

#1603 fix: Unary Callables Deadline values respect the TotalTimeout in RetrySettings
  .github/workflows/sonar.yaml
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonCallOptions.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCallImpl.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCalls.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpRequestRunnable.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ManagedHttpJsonChannel.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectCallableTest.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpRequestRunnableTest.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/testing/MockHttpService.java
  gax-java/gax/src/main/java/com/google/api/gax/longrunning/OperationTimedPollAlgorithm.java
  gax-java/gax/src/main/java/com/google/api/gax/retrying/ExponentialRetryAlgorithm.java
  gax-java/gax/src/test/java/com/google/api/gax/retrying/ExponentialRetryAlgorithmTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITLongRunningOperation.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryDeadline.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/TestClientInitializer.java
  showcase/pom.xml
Labels: size: xl

#1670 chore: update protobuf dependency to match workspace
  gax-java/dependencies.properties
Labels: size: xs

#1676 chore: rename repo to `sdk-platform-java`
  README.md
  gapic-generator-java-pom-parent/pom.xml
  gapic-generator-java/DEVELOPMENT.md
  gapic-generator-java/pom.xml
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/grpc/ServiceClientTestClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/HttpRuleParserTest.java
  gapic-generator-java/src/test/proto/http_rule_parser_testing.proto
  java-common-protos/proto-google-common-protos/src/main/java/com/google/api/MethodSettings.java
  java-common-protos/proto-google-common-protos/src/main/proto/google/api/client.proto
  java-core/.repo-metadata.json
Labels: size: s

#1648 test: refactor test-related helpers for gapic-generator-java for inclusion in testlib jar
  gapic-generator-java/pom.xml
  gapic-generator-java/src/test/java/com/google/api/generator/engine/JavaCodeGeneratorTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/ast/ArrayExprTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/ast/JavaDocCommentTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/writer/ImportWriterVisitorTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/ClientLibraryPackageInfoComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/ComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/common/BatchingDescriptorComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/common/RetrySettingsComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceCallableFactoryClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/MockServiceClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/MockServiceImplClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceClientClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceClientTestClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/GrpcServiceCallableFactoryClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/GrpcServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/HttpJsonServiceCallableFactoryClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/HttpJsonServiceClientTestClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/HttpJsonServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientTestClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceStubSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceCallableFactoryClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/ServiceClientTestClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/ServiceSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/ServiceStubSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/SampleBodyJavaFormatterTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/SampleCodeWriterTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/SampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientCallableMethodSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientMethodSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/SettingsSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/utils/CommentFormatterTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/model/RegionTagTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/framework/Assert.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/framework/GoldenFileWriter.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/GrpcRestTestProtoLoader.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/GrpcTestProtoLoader.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/RestTestProtoLoader.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/TestProtoLoader.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/utils/LineFormatter.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/utils/TestExprBuilder.java
  gapic-generator-java/src/test/java/com/google/api/generator/util/TrieTest.java
Labels: size: m

#1681 test: use Java 17 to produce Java 8-compatible bytecode
  .github/workflows/ci.yaml
  .kokoro/release/common.cfg
Labels: size: s

#1689 chore: exclude .iml files in showcase's `verify.sh` diff check
  showcase/scripts/verify.sh
Labels: size: xs

#1692 feat: Create additional tag on release for google-cloud-shared-dependencies
  .github/workflows/create_additional_release_tag.yaml
Labels: size: s

#1690 chore: add 2 minute timeout to GrpcDirectStreamControllerTest
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectStreamControllerTest.java
Labels: size: xs

#1699 fix: update tag workflow
  .github/workflows/create_additional_release_tag.yaml
Labels: size: s

#1700 fix: fix release tag workflow to fetch all tags first
  .github/workflows/create_additional_release_tag.yaml
Labels: size: xs

#1703 chore: add workaround for sonatype issue with Java 17
  .kokoro/release/stage.sh
Labels: automerge, size: xs

#1688 fix: Allow quota project to be used in combination with null credentials
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
Labels: size: s

#1714 Revert "chore: [iam] upgrading Protobuf to 23.1 and gRPC to 1.55.0 in code generation"
  java-iam/proto-google-iam-v1/clirr-ignored-differences.xml
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/AuditConfig.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/AuditConfigDelta.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/AuditLogConfig.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/Binding.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/BindingDelta.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/BindingOrBuilder.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/GetIamPolicyRequest.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/GetPolicyOptions.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/GetPolicyOptionsOrBuilder.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/IamPolicyProto.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/Policy.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/PolicyDelta.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/PolicyOrBuilder.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/SetIamPolicyRequest.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/SetIamPolicyRequestOrBuilder.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/TestIamPermissionsRequest.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/TestIamPermissionsResponse.java
  java-iam/proto-google-iam-v2/clirr-ignored-differences.xml
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/CreatePolicyRequest.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/CreatePolicyRequestOrBuilder.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/DeletePolicyRequest.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/DeletePolicyRequestOrBuilder.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/DenyRule.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/DenyRuleOrBuilder.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/GetPolicyRequest.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/GetPolicyRequestOrBuilder.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/ListPoliciesRequest.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/ListPoliciesRequestOrBuilder.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/ListPoliciesResponse.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/Policy.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/PolicyOperationMetadata.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/PolicyOrBuilder.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/PolicyProto.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/PolicyRule.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/PolicyRuleOrBuilder.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/UpdatePolicyRequest.java
  java-iam/proto-google-iam-v2/src/main/java/com/google/iam/v2/UpdatePolicyRequestOrBuilder.java
  java-iam/proto-google-iam-v2beta/clirr-ignored-differences.xml
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/CreatePolicyRequest.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/CreatePolicyRequestOrBuilder.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/DeletePolicyRequest.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/DeletePolicyRequestOrBuilder.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/DenyRule.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/DenyRuleOrBuilder.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/GetPolicyRequest.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/GetPolicyRequestOrBuilder.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/ListPoliciesRequest.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/ListPoliciesRequestOrBuilder.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/ListPoliciesResponse.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/Policy.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/PolicyOperationMetadata.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/PolicyOrBuilder.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/PolicyProto.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/PolicyRule.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/PolicyRuleOrBuilder.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/UpdatePolicyRequest.java
  java-iam/proto-google-iam-v2beta/src/main/java/com/google/iam/v2beta/UpdatePolicyRequestOrBuilder.java
Labels: size: xl

#1718 chore: temporarily turning off Renovate Bot until August
  renovate.json
Labels: automerge, size: xs
