Repository googleapis/sdk-platform-java, pull requests merged in 2023-04, with the labels that each got.

#1597 chore: Update showcase to latest version
  .github/workflows/ci.yaml
  .github/workflows/downstream-native-image.yaml
  .github/workflows/sonar.yaml
  renovate.json
  showcase/README.md
  showcase/gapic-showcase/pom.xml
Labels: size: s

#1602 chore: add showcase coverage to full project coverage report
  .github/workflows/sonar.yaml
  coverage-report/README.md
  gapic-generator-java-pom-parent/pom.xml
  gapic-generator-java/pom.xml
  java-common-protos/pom.xml
  java-iam/pom.xml
  pom.xml
Labels: size: m

#1572 chore: add script to create a native image submodule for testing
  scripts/create_native_image_test_env.sh
Labels: size: m

#1604 test: Add BIDI streaming showcase test.
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITBidiStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITClientSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryCallable.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/TestClientInitializer.java
Labels: size: m

#1609 fix: add javadoc for `ApiFutures`
  api-common-java/src/main/java/com/google/api/core/ApiFutures.java
Labels: size: m

#1610 build: Update Bazel version to 6.0.0 in .bazeliskrc
  .bazeliskrc
Labels: size: xs

#1621 fix(deps): remove unnecessary auto-value in api-common-java
  api-common-java/pom.xml
Labels: size: xs

#1575 feat: add stream method for `ServerStream`
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ServerStream.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ServerStreamTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
Labels: size: m

#1515 feat: add `FunctionalInterface` annotation
  api-common-java/src/main/java/com/google/api/core/ApiAsyncFunction.java
  api-common-java/src/main/java/com/google/api/core/ApiFunction.java
  api-common-java/src/main/java/com/google/api/pathtemplate/ValidationException.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/FieldsExtractor.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/BidiStreamingCallable.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientStreamReadyObserver.java
Labels: size: s

#1617 chore: fix syntax in native image submodule script
  scripts/create_native_image_test_env.sh
Labels: size: xs

#1425 feat: add stream methods for `Page`
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/paging/Page.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/PagingTest.java
Labels: size: m

#1583 chore: Fix testCancelOuterFutureBeforeStart flaky test
  gax-java/gax/src/test/java/com/google/api/gax/retrying/AbstractRetryingExecutorTest.java
  gax-java/gax/src/test/java/com/google/api/gax/retrying/FailingCallable.java
  gax-java/gax/src/test/java/com/google/api/gax/retrying/ScheduledRetryingExecutorTest.java
Labels: size: s

#1628 chore: Close gRPC Identity client
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITCrud.java
Labels: size: xs

#1586 chore: handle FlowControllerTest thread start variation by polling
  gax-java/gax/src/test/java/com/google/api/gax/batching/AssertByPolling.java
  gax-java/gax/src/test/java/com/google/api/gax/batching/AssertByPollingTest.java
  gax-java/gax/src/test/java/com/google/api/gax/batching/FlowControllerTest.java
Labels: size: m

#1646 chore: fix links in README
  README.md
Labels: size: xs

#1645 feat(deps): add gapic-generator-java to bom
  gapic-generator-java-bom/pom.xml
Labels: size: xs

#1625 chore: migrate showcase tests job for graalvm from GA to kokoro
  .github/workflows/downstream-native-image.yaml
  .kokoro/presubmit/downstream-build.sh
  renovate.json
Labels: size: m

#1654 fix: Unescape Java keyword field names when generating HttpJson unit tests.
  gapic-generator-java/src/main/java/com/google/api/generator/engine/lexicon/Keyword.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/utils/JavaStyle.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/lexicon/KeywordTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientHttpJsonTest.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientTest.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/GrpcEchoStub.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/HttpJsonEchoStub.golden
  gapic-generator-java/src/test/proto/echo_grpcrest.proto
Labels: size: l

#1644 test: use a tag in validating gapic-generator-java-bom
  .github/workflows/ci.yaml
Labels: size: xs

#1651 chore: reduce sleep count in AssertByPollingTest
  gax-java/gax/src/test/java/com/google/api/gax/batching/AssertByPollingTest.java
Labels: size: s

#1656 chore: Add HttpJson Showcase test for Location Mixins
  .github/workflows/ci.yaml
  .github/workflows/sonar.yaml
  .kokoro/presubmit/downstream-build.sh
  showcase/README.md
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITCommonServiceMixins.java
Labels: size: m
