Repository googleapis/sdk-platform-java, pull requests merged in 2023-02, with the labels that each got.

#1237 doc: Update DEVELOPMENT.md for local development.
  DEVELOPMENT.md
Labels: automerge

#1305 chore: removing unused Gradle files in api-common-java, gax-java, java-common-protos, and java-iam
  api-common-java/build.gradle
  api-common-java/gradle/wrapper/gradle-wrapper.jar
  api-common-java/gradle/wrapper/gradle-wrapper.properties
  api-common-java/gradlew
  api-common-java/gradlew.bat
  gax-java/build.gradle
  gax-java/gax-bom/build.gradle
  gax-java/gax-grpc/build.gradle
  gax-java/gax-httpjson/build.gradle
  gax-java/gax/build.gradle
  gax-java/gradle/wrapper/gradle-wrapper.jar
  gax-java/gradle/wrapper/gradle-wrapper.properties
  gax-java/gradlew
  gax-java/gradlew.bat
  gax-java/settings.gradle
  java-common-protos/grpc-google-common-protos/build.gradle
  java-common-protos/proto-google-common-protos/build.gradle
  java-iam/grpc-google-iam-v1/build.gradle
  java-iam/proto-google-iam-v1/build.gradle
Labels: automerge, size: xl

#1334 chore: updated gax-java contribution doc
  api-common-java/CODE_OF_CONDUCT.md
  api-common-java/CONTRIBUTING.md
  api-common-java/README.md
  api-common-java/RELEASING.md
  api-common-java/SECURITY.md
  api-common-java/renovate.json
  api-common-java/synth.metadata
  gax-java/CODE_OF_CONDUCT.md
  gax-java/CONTRIBUTING.md
  gax-java/RELEASING.md
  gax-java/SECURITY.md
  java-common-protos/CODE_OF_CONDUCT.md
  java-common-protos/CONTRIBUTING.md
  java-common-protos/renovate.json
  java-common-protos/synth.metadata
  java-iam/CODE_OF_CONDUCT.md
  java-iam/CONTRIBUTING.md
  java-iam/README.md
  java-iam/renovate.json
  java-iam/synth.metadata
Labels: size: xl

#1303 fix: use pkg_tar from rules_pkg
  WORKSPACE
  rules_java_gapic/BUILD.bazel
Labels: size: s

#1343 fix(spring): update hasRestOption to exclude services with no rest-supported methods
  src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java
Labels: spring, size: s

#1294 chore: Fix pre-commit.
  .githooks/pre-commit
  DEVELOPMENT.md
Labels: size: s

#1346 chore: update CONTRIBUTING.md
  gax-java/CONTRIBUTING.md
Labels: size: xs

#1349 chore: add rules_pkg to renovate bot ignoreDeps
  renovate.json
Labels: automerge, size: xs

#1353 chore: fix renovate bot ignoreDeps
  renovate.json
Labels: automerge, size: xs

#1166 fix(batcher): exceptions in unaryCaller bubble up
  gax-java/gax/src/main/java/com/google/api/gax/batching/BatcherImpl.java
  gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: size: m

#1351 chore: refactoring README and DEVELOPMENT.md
  DEVELOPMENT.md
  README.md
  gapic-generator-java/DEVELOPMENT.md
  gapic-generator-java/README.md
  gax-java/CONTRIBUTING.md
  gax-java/DEVELOPMENT.md
  gax-java/README.md
  showcase/README.md
Labels: automerge, size: l

#1362 chore: renovate to group Protobuf artifacts
  renovate.json
Labels: automerge, size: m

#1348 fix(spring): extend hasRestOption fix to properties composer and add golden tests
  src/main/java/com/google/api/generator/spring/composer/SpringPropertiesClassComposer.java
  src/main/java/com/google/api/generator/spring/composer/comment/SpringAutoconfigCommentComposer.java
  src/test/java/com/google/api/generator/gapic/composer/grpcrest/GrpcRestTestProtoLoader.java
  src/test/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposerTest.java
  src/test/java/com/google/api/generator/spring/composer/SpringPropertiesClassComposerTest.java
  src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden
  src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden
  src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
  src/test/java/com/google/api/generator/spring/composer/goldens/WickedSpringAutoConfigurationNoRestRpcs.golden
  src/test/java/com/google/api/generator/spring/composer/goldens/WickedSpringPropertiesNoRestRpcs.golden
  src/test/proto/wicked.proto
Labels: spring, size: l

#1361 chore: README.md to explain service_config.proto
  gapic-generator-java/README.md
Labels: size: s

#1372 chore: Telling owlbot to ignore these files & it's a monorepo
  java-common-protos/owlbot.py
  java-iam/owlbot.py
Labels: size: s

#1370 chore: update gcp-releasetool to 1.10.5
  .kokoro/requirements.in
  .kokoro/requirements.txt
Labels: automerge, size: s
