Repository googleapis/sdk-platform-java, pull requests merged in 2023-03, with the labels that each got.

#1378 chore: Trying to create issues in nightly build
  .github/workflows/nightly.yaml
Labels: size: s

#1436 chore: Disabling major version updates for all dependencies
  renovate.json
Labels: size: xs

#1441 chore: adding description of gax, gax-grpc, gax-httpjson
  gax-java/README.md
Labels: automerge, size: s

#1442 chore: importing gax-java's Renovate configuration with regex
  renovate.json
Labels: automerge, size: s

#1281 chore: consistent use of bazelisk over bazel
  test/integration/goldens/README.md
Labels: size: s

#1464 chore: group com.google.api and com.google.http-client dependencies in RenovateBot config
  renovate.json
Labels: automerge, size: s

#1454 chore: instructions on debuging the `gapic-generator-java` running on protobuf compiler
  gapic-generator-java/DEVELOPMENT.md
  gapic-generator-java/debug.png
Labels: size: s

#1474 chore: declare test-jar in GAX's testlib artifacts
  gapic-generator-java/pom.xml
  gax-java/gax-bom/pom.xml
Labels: size: s

#1430 chore: add aggregate test coverage collection of gax within the showcase and gax modules
  .github/workflows/ci-maven.yaml
  coverage-report/README.md
  coverage-report/pom.xml
  gapic-generator-java-pom-parent/pom.xml
  pom.xml
  showcase/gapic-showcase/pom.xml
Labels: size: m

#1508 feat: install compatibility check
  .github/workflows/ci-maven.yaml
Labels: size: s

#1519 chore: rename ci-maven workflow to ci
  .github/workflows/ci.yaml
Labels: size: xs

#1525 chore: Update gapic-showcase to v0.26.0
  .github/workflows/ci.yaml
  .github/workflows/downstream-native-image.yaml
  WORKSPACE
  showcase/README.md
Labels: size: s

#1533 chore: Fix unicode flaky test with utf-8 as default charset
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpRequestRunnableTest.java
Labels: size: xs

#1536 chore: update graalvm downstream presubmit after java-core and share-dependencies migration
  .kokoro/presubmit/downstream-build.sh
Labels: size: s

#1538 chore: api-common-java and gax-java use SPDX identifier for BSD-3-Clause license
  api-common-java/LICENSE
  api-common-java/pom.xml
  gax-java/LICENSE
  gax-java/gax-bom/pom.xml
  gax-java/pom.xml
Labels: size: s

#1501 chore: add unary-unary showcase test for gRPC support
  .github/workflows/ci.yaml
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITFirstHttp.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITFirstRpc.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITNumericEnums.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryCallable.java
Labels: size: l

#1535 ci: installing shared dependencies BOM upper-bound check
  .github/workflows/shared_dependencies.yaml
  gapic-generator-java-pom-parent/pom.xml
Labels: size: s

#1537 fix: Fix race condition in GrpcDirectStreamController
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcDirectStreamController.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectStreamControllerTest.java
Labels: size: m

#1483 chore: Add Showcase Callables IT
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryCallable.java
Labels: size: s

#1552 chore: fix java-core/.repo-metadata.json
  java-core/.repo-metadata.json
Labels: automerge, size: xs

#1548 chore: include showcase module in test coverage report
  coverage-report/README.md
  coverage-report/pom.xml
  showcase/pom.xml
Labels: size: s

#1502 chore: add showcase test for server-side with gRPC transport
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
Labels: size: m

#1522 fix: Validate paths and check additionalPathTemplates
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ProtoMessageRequestFormatter.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/ProtoMessageRequestFormatterTest.java
Labels: size: s

#1539 chore: Update steps to generate a library locally
  gapic-generator-java/DEVELOPMENT.md
Labels: size: s

#1555 chore: coverage-report/pom.xml to have api-common annotation
  coverage-report/pom.xml
Labels: size: xs

#1581 chore: Renovate bot should not update this dependency.
  java-iam/pom.xml
Labels: size: xs

#1584 chore: remove java-common-protos/.kokoro and enable renovate bot for requirements file.
  .github/workflows/ci.yaml
  .kokoro/requirements.in
  .kokoro/requirements.txt
  java-common-protos/.kokoro/build.bat
  java-common-protos/.kokoro/build.sh
  java-common-protos/.kokoro/coerce_logs.sh
  java-common-protos/.kokoro/common.cfg
  java-common-protos/.kokoro/common.sh
  java-common-protos/.kokoro/continuous/common.cfg
  java-common-protos/.kokoro/continuous/java8.cfg
  java-common-protos/.kokoro/nightly/common.cfg
  java-common-protos/.kokoro/nightly/integration.cfg
  java-common-protos/.kokoro/nightly/java11-integration.cfg
  java-common-protos/.kokoro/nightly/java11.cfg
  java-common-protos/.kokoro/nightly/java7.cfg
  java-common-protos/.kokoro/nightly/java8-osx.cfg
  java-common-protos/.kokoro/nightly/java8-win.cfg
  java-common-protos/.kokoro/nightly/java8.cfg
  java-common-protos/.kokoro/nightly/samples.cfg
  java-common-protos/.kokoro/populate-secrets.sh
  java-common-protos/.kokoro/presubmit/clirr.cfg
  java-common-protos/.kokoro/presubmit/common.cfg
  java-common-protos/.kokoro/presubmit/dependencies.cfg
  java-common-protos/.kokoro/presubmit/graalvm-native-17.cfg
  java-common-protos/.kokoro/presubmit/graalvm-native.cfg
  java-common-protos/.kokoro/presubmit/integration.cfg
  java-common-protos/.kokoro/presubmit/java11.cfg
  java-common-protos/.kokoro/presubmit/java7.cfg
  java-common-protos/.kokoro/presubmit/java8-osx.cfg
  java-common-protos/.kokoro/presubmit/java8-win.cfg
  java-common-protos/.kokoro/presubmit/java8.cfg
  java-common-protos/.kokoro/presubmit/linkage-monitor.cfg
  java-common-protos/.kokoro/presubmit/lint.cfg
  java-common-protos/.kokoro/presubmit/samples.cfg
  java-common-protos/.kokoro/release/bump_snapshot.cfg
  java-common-protos/.kokoro/release/common.cfg
  java-common-protos/.kokoro/release/common.sh
  java-common-protos/.kokoro/release/drop.cfg
  java-common-protos/.kokoro/release/drop.sh
  java-common-protos/.kokoro/release/promote.cfg
  java-common-protos/.kokoro/release/promote.sh
  java-common-protos/.kokoro/release/publish_javadoc.cfg
  java-common-protos/.kokoro/release/publish_javadoc.sh
  java-common-protos/.kokoro/release/publish_javadoc11.cfg
  java-common-protos/.kokoro/release/publish_javadoc11.sh
  java-common-protos/.kokoro/release/snapshot.cfg
  java-common-protos/.kokoro/release/snapshot.sh
  java-common-protos/.kokoro/release/stage.cfg
  java-common-protos/.kokoro/release/stage.sh
  java-common-protos/.kokoro/requirements.in
  java-common-protos/.kokoro/requirements.txt
  java-common-protos/.kokoro/trampoline.sh
  renovate.json
Labels: size: l

#1568 chore: Add Showcase Http Annotations Test
  .github/workflows/sonar.yaml
  .gitignore
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITHttpAnnotation.java
  showcase/gapic-showcase/src/test/resources/META-INF/native-image/resource-config.json
  showcase/gapic-showcase/src/test/resources/compliance_suite.json
  showcase/scripts/verify.sh
Labels: size: l

#1582 chore: add client-side streaming showcase integration tests for gRPC support
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITClientSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryCallable.java
Labels: size: m

#1588 chore: Add httpjson server-side streaming showcase tests
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
Labels: size: m
