Repository googleapis/sdk-platform-java, pull requests merged in 2023-11, with the labels that each got.

#1863 docs: Update RetrySettings javadocs to include polling
  gax-java/gax/src/main/java/com/google/api/gax/retrying/RetrySettings.java
Labels: size: m

#2235 fix: confirm owlbot-copy succeeeded to transfer java files
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/resources/proto_path_list.txt
Labels: size: s

#2234 chore: update showcase version
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/SequenceServiceClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/gapic_metadata.json
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/EchoStub.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/EchoStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/GrpcEchoStub.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonEchoStub.java
  showcase/gapic-showcase/src/main/resources/META-INF/native-image/com.google.showcase.v1beta1/reflect-config.json
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoGrpc.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/AttemptStreamingSequenceRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/AttemptStreamingSequenceRequestOrBuilder.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoErrorDetailsRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoErrorDetailsRequestOrBuilder.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoErrorDetailsResponse.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoErrorDetailsResponseOrBuilder.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoOuterClass.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ErrorWithMultipleDetails.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ErrorWithMultipleDetailsOrBuilder.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ErrorWithSingleDetail.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ErrorWithSingleDetailOrBuilder.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/SequenceOuterClass.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/StreamingSequenceReport.java
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/echo.proto
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/sequence.proto
Labels: size: xl

#2114 feat: update javadocs for Client classes to include table of methods
  .github/workflows/ci.yaml
  gapic-generator-java/DEVELOPMENT.md
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/comment/ServiceClientCommentComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/writer/goldens/GrpcServiceClientWithNestedClassImport.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/BookshopClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/IdentityClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/MessagingClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoEmpty.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/WickedClient.golden
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/ComplianceClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/IdentityClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/MessagingClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/SequenceServiceClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/TestingClient.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/ConnectionServiceClient.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/TetherClient.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/AssetServiceClient.java
  test/integration/goldens/bigtable/src/com/google/cloud/bigtable/data/v2/BaseBigtableDataClient.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/AddressesClient.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/RegionOperationsClient.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/IamCredentialsClient.java
  test/integration/goldens/iam/src/com/google/iam/v1/IAMPolicyClient.java
  test/integration/goldens/kms/src/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/LibraryServiceClient.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/ConfigClient.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/LoggingClient.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/MetricsClient.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/SchemaServiceClient.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/TopicAdminClient.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/CloudRedisClient.java
  test/integration/goldens/storage/src/com/google/storage/v2/StorageClient.java
Labels: size: xl

#2010 chore: remove unused release jobs
  .github/workflows/ci.yaml
  .kokoro/release/common.cfg
  .kokoro/release/common.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  .kokoro/requirements.in
Labels: size: l

#2268 chore: remove requirements.txt
  .kokoro/requirements.txt
Labels: size: l

#2252 fix: owlbot-cli image sha to be locked (hermetic)
  library_generation/configuration/owlbot-cli-sha
  library_generation/postprocess_library.sh
Labels: size: xs

#2272 build: do not declare javadoc plugin version
  java-common-protos/pom.xml
  java-iam/pom.xml
Labels: size: xs

#2271 Revert "deps: update dependency com.googlecode.maven-download-plugin:download-maven-plugin to v1.7.1"
  gapic-generator-java/pom.xml
  showcase/gapic-showcase/pom.xml
Labels: size: xs
