Repository googleapis/sdk-platform-java, pull requests merged in 2023-06, with the labels that each got.

#1677 feat: Implement awaitTermination() for MangedHttpJsonChannel
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/InstantiatingHttpJsonChannelProvider.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ManagedHttpJsonChannel.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ManagedHttpJsonInterceptorChannel.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/InstantiatingHttpJsonChannelProviderTest.java
  gax-java/gax/src/main/java/com/google/api/gax/core/InstantiatingExecutorProvider.java
Labels: size: m

#1669 chore: Shutdown and awaitTermination for showcase clients
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITBidiStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITClientSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITCommonServiceMixins.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITCrud.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITHttpAnnotation.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITLongRunningOperation.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITNumericEnums.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryCallable.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryDeadline.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/TestClientInitializer.java
  showcase/pom.xml
Labels: size: l

#1754 build: fix sonatype repository addresses
  java-common-protos/pom.xml
  java-iam/pom.xml
  pom.xml
Labels: size: s

#1751 fix: update the return type of setWaitTimeout for convience
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ServerStreamingCallSettings.java
Labels: automerge, size: xs

#1756 deps: update dependency com.google.auth:google-auth-library-credentials and google-auth-library-oauth2-http to v1.17.0
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
Labels: size: xs

#1753 feat: dynamically determine protobuf version in build.gradle
  gax-java/dependencies.properties
  rules_java_gapic/java_gapic_pkg.bzl
Labels: size: s

#1747 doc: Add test guide to DEVELOPMENT.md
  DEVELOPMENT.md
Labels: size: s

#1691 chore: Clean up resources in gRPCStreamDirectController and ChannelPool tests
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/ChannelPoolTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectStreamControllerTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/testing/FakeServiceImpl.java
Labels: size: m

#1779 chore: copy and update PROPERTIES using widely supported syntax
  rules_java_gapic/java_gapic_pkg.bzl
Labels: size: xs

#1264 feat: GA Gax HttpJson
  coverage-report/pom.xml
  gax-java/dependencies.properties
  gax-java/gax-bom/pom.xml
  gax-java/gax-httpjson/pom.xml
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ApiMethodDescriptor.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ForwardingHttpJsonClientCall.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ForwardingHttpJsonClientCallListener.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonCallContext.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonCallOptions.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonChannel.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCall.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientInterceptor.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonHeaderEnhancer.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonHeaderEnhancers.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonInterceptorProvider.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonMetadata.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonOperationSnapshot.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonOperationSnapshotCallable.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonStatusCode.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpRequestFormatter.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/InstantiatingHttpJsonChannelProvider.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ManagedHttpJsonChannel.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ManagedHttpJsonInterceptorChannel.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ProtoMessageRequestFormatter.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ProtoRestSerializer.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/RestSerializationException.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/longrunning/OperationsClient.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/longrunning/OperationsSettings.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/longrunning/stub/HttpJsonOperationsCallableFactory.java
  versions.txt
Labels: size: m

#1794 fix: update grpc to 1.55.1 in dependencies.properties
  gax-java/dependencies.properties
Labels: size: xs

#1791 build(deps): bump guava to 32.0.1-jre, google-http-client to 1.43.3.
  gapic-generator-java-pom-parent/pom.xml
  gapic-generator-java/pom.xml
  gax-java/dependencies.properties
  gax-java/gax-httpjson/pom.xml
  gax-java/pom.xml
  java-common-protos/pom.xml
  java-core/google-cloud-core/pom.xml
  java-shared-dependencies/dependency-convergence-check/pom.xml
  java-shared-dependencies/first-party-dependencies/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
  java-shared-dependencies/upper-bound-check/pom.xml
Labels: size: m

#1793 build(deps): bump google-auth-library to 1.18.0
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
Labels: size: xs

#1790 fix: abstract batch resource and add method to determine if batch should be flushed
  gax-java/gax/pom.xml
  gax-java/gax/src/main/java/com/google/api/gax/batching/BatchResource.java
  gax-java/gax/src/main/java/com/google/api/gax/batching/BatcherImpl.java
  gax-java/gax/src/main/java/com/google/api/gax/batching/BatchingDescriptor.java
  gax-java/gax/src/main/java/com/google/api/gax/batching/DefaultBatchResource.java
  gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: automerge, size: m

#1805 ci: add showcase-clirr check
  .github/workflows/ci.yaml
Labels: size: s

#1802 chore: Update gax-httpjson version in README
  gax-java/README.md
Labels: size: xs

#1815 deps: update google-auth-java-library to 1.19.0
  gapic-generator-java-pom-parent/pom.xml
Labels: size: xs

#1642 feat: support GDC-H Credentials
  gax-java/.gitignore
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientSettings.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITGdch.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/InterceptingMockTokenServerTransport.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/InterceptingMockTokenServerTransportFactory.java
  showcase/gapic-showcase/src/test/resources/fake_cert.pem
  showcase/gapic-showcase/src/test/resources/test_gdch_credential.json
Labels: size: l
