Repository googleapis/sdk-platform-java, pull requests merged in 2023-08, with the labels that each got.

#1911 ci: use java 17 with sonar
  .github/workflows/sonar.yaml
Labels: size: xs

#1884 ci: configure the 2.23.x protected branch
  .github/workflows/ci.yaml
  .github/workflows/shared_dependencies.yaml
  .github/workflows/sonar.yaml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITGdch.java
  showcase/gapic-showcase/src/test/resources/META-INF/native-image/resource-config.json
Labels: size: m

#1926 ci: showcase now uses shared-dependencies
  gapic-generator-java-bom/pom.xml
  showcase/gapic-showcase/pom.xml
  showcase/pom.xml
Labels: size: s

#1909 ci: add downstream compatibility checks
  .github/workflows/ci.yaml
  .kokoro/presubmit/common.sh
  .kokoro/presubmit/common_test.sh
  .kokoro/presubmit/downstream-build.sh
  .kokoro/presubmit/downstream-compatibility.sh
Labels: size: l

#1915 chore: Resolve flaky HttpJsonDirectServerStreamingCallableTest test
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
Labels: size: s

#1929 chore: add comments to showcase grpc library
  showcase/gapic-showcase/pom.xml
  showcase/grpc-gapic-showcase-v1beta1/pom.xml
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ComplianceGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/IdentityGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/MessagingGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/SequenceServiceGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/TestingGrpc.java
  showcase/proto-gapic-showcase-v1beta1/pom.xml
Labels: size: l

#1916 feat: add `generate_library.sh` without post processing
  .github/workflows/verify_library_generation.yaml
  library_generation/README.md
  library_generation/gapic-generator-java-wrapper
  library_generation/generate_library.sh
  library_generation/generate_library_integration_test.sh
  library_generation/utilities.sh
Labels: size: l

#1943 chore: clean up hermetic build script and test
  .github/workflows/verify_library_generation.yaml
  library_generation/README.md
  library_generation/gapic-generator-java-wrapper
  library_generation/generate_library.sh
  library_generation/generate_library_integration_test.sh
  library_generation/utilities.sh
Labels: size: m

#1940 chore: Clean up renovate.json in gax module.
  gax-java/renovate.json
Labels: size: s
