Repository googleapis/sdk-platform-java, pull requests merged in 2023-12, with the labels that each got.

#2278 feat: Structs mapper utility
  java-core/google-cloud-core/src/main/java/com/google/cloud/Structs.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/StructsTest.java
Labels: size: l

#2289 chore: modify instructions on how to update goldens
  showcase/README.md
  test/integration/goldens/README.md
Labels: size: s

#2285 test: BatcherImplTest.testThrottlingBlocking to check actual wait time
  gax-java/gax/pom.xml
  gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: size: s

#2275 refactor: Add EndpointContext
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
Labels: size: l

#2280 fix: format proto comments in Client Overview
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/comment/ServiceClientCommentComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/writer/goldens/GrpcServiceClientWithNestedClassImport.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/BookshopClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/IdentityClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/MessagingClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/WickedClient.golden
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/ComplianceClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/IdentityClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/MessagingClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/SequenceServiceClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/TestingClient.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/ConnectionServiceClient.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/TetherClient.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/AssetServiceClient.java
  test/integration/goldens/bigtable/src/com/google/cloud/bigtable/data/v2/BaseBigtableDataClient.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/AddressesClient.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/RegionOperationsClient.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/IamCredentialsClient.java
  test/integration/goldens/iam/src/com/google/iam/v1/IAMPolicyClient.java
  test/integration/goldens/kms/src/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/LibraryServiceClient.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/ConfigClient.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/LoggingClient.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/MetricsClient.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/SchemaServiceClient.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/TopicAdminClient.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/CloudRedisClient.java
  test/integration/goldens/storage/src/com/google/storage/v2/StorageClient.java
Labels: size: xl

#2291 test: increasing timeout in testOnResponseError
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
Labels: size: xs

#2298 chore: add cloudbuild setup to publish docker images
  .cloudbuild/cloudbuild-test-a.yaml
  .cloudbuild/cloudbuild-test-b.yaml
  .cloudbuild/cloudbuild.yaml
  .cloudbuild/google-cloud-sdk.repo
  .cloudbuild/graalvm_a.Dockerfile
  .cloudbuild/graalvm_b.Dockerfile
  renovate.json
Labels: size: m

#2308 test: increasing timeout in testServerStreamingStart
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
Labels: size: xs

#2282 feat: move Java Owlbot into this repository for postprocessing
  .github/workflows/verify_library_generation.yaml
  library_generation/README.md
  library_generation/configuration/python-version
  library_generation/configuration/synthtool-commitish
  library_generation/generate_library.sh
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/owlbot/bin/write_clirr_ignore.sh
  library_generation/owlbot/src/fix-license-headers.py
  library_generation/owlbot/src/fix-poms.py
  library_generation/owlbot/src/gen-template.py
  library_generation/owlbot/src/poms/.gitignore
  library_generation/owlbot/src/poms/module.py
  library_generation/owlbot/src/poms/templates.py
  library_generation/owlbot/src/requirements.in
  library_generation/owlbot/src/requirements.txt
  library_generation/owlbot/templates/clirr/clirr-ignored-differences.xml.j2
  library_generation/owlbot/templates/poms/bom_pom.xml.j2
  library_generation/owlbot/templates/poms/cloud_pom.xml.j2
  library_generation/owlbot/templates/poms/grpc_pom.xml.j2
  library_generation/owlbot/templates/poms/parent_pom.xml.j2
  library_generation/owlbot/templates/poms/proto_pom.xml.j2
  library_generation/owlbot/templates/poms/versions.txt.j2
  library_generation/postprocess_library.sh
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/proto_path_library/proto-test-library/src/main/proto/google/cloud/test/v1/empty.proto
  library_generation/test/resources/proto_path_library_multiple_protos/proto-1/fake.proto
  library_generation/test/resources/proto_path_library_multiple_protos/proto-2/fake.proto
  library_generation/test/resources/proto_path_list.txt
  library_generation/utilities.sh
Labels: size: xl, hermetic-build

#2300 feat: Parse Host Service Name
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/comment/SettingsCommentComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/Service.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingServiceV2StubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/PublisherStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/model/ServiceTest.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/ConnectionServiceStubSettings.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/TetherStubSettings.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  test/integration/goldens/bigtable/src/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/AddressesStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/RegionOperationsStubSettings.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java
  test/integration/goldens/iam/src/com/google/iam/v1/stub/IAMPolicyStubSettings.java
  test/integration/goldens/kms/src/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/stub/LibraryServiceStubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  test/integration/goldens/storage/src/com/google/storage/v2/stub/StorageStubSettings.java
Labels: size: m

#2299 chore: Update ci.yaml to setup Java 21 CI tests
  .bazeliskrc
  .github/workflows/ci.yaml
Labels: size: s

#2312 feat: add parsing of autopopulated fields from serviceyaml
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/Field.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/Method.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoClientTest.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncChat.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncChatAgain.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncCollect.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncCollideName.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncEcho.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncExpand.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/SyncCollideName.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/SyncEcho.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientCallableMethodSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientMethodSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/model/MethodTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ServiceYamlParserTest.java
  gapic-generator-java/src/test/proto/echo.proto
  gapic-generator-java/src/test/resources/echo_v1beta1.yaml
Labels: size: l
