Repository googleapis/sdk-platform-java, pull requests merged in 2024-08, with the labels that each got.

#3075 fix: Generator callable generation is based on method type
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractTransportServiceStubClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/GrpcCallableNameTypeStub.golden
  gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/TestProtoLoader.java
  gapic-generator-java/src/test/proto/callable_name_type.proto
Labels: size: l

#3087 chore: Clarify testing guide in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: size: xs

#3090 chore: Re-run renovate-config-validator
  library_generation/owlbot/templates/java_library/renovate.json
Labels: size: s

#3130 chore: remove image tag in hermetic code generation workflow
  .github/scripts/hermetic_library_generation.sh
  .github/workflows/hermetic_library_generation.yaml
  generation_config.yaml
Labels: size: s

#3136 chore: remove unused templates
  library_generation/owlbot/templates/java_library/.github/generated-files-bot.yml
Labels: size: s

#3106 chore(templates/java_library): close maven dependencies tag in bom snippet
  library_generation/owlbot/templates/java_library/README.md
Labels: owlbot:ignore, size: xs

#3126 docs: Update DEVELOPMENT.md
  gapic-generator-java/DEVELOPMENT.md
Labels: size: m

#3095 fix(gax): prevent truncation/overflow when converting time values
  gax-java/gax/src/main/java/com/google/api/gax/util/TimeConversionUtils.java
  gax-java/gax/src/test/java/com/google/api/gax/util/TimeConversionUtilsTest.java
Labels: size: s

#3092 test: add downstream check for spring-cloud-gcp
  .github/workflows/downstream.yaml
  .kokoro/presubmit/common.sh
  .kokoro/presubmit/downstream-compatibility-spring.sh
  .kokoro/presubmit/downstream-compatibility.sh
Labels: automerge, size: m

#3142 chore: remove mac unit tests in library generation ci
  .github/workflows/verify_library_generation.yaml
Labels: size: s

#3072 chore: generate poms with grpc dependencies as test scoped
  library_generation/owlbot/src/fix_poms.py
  library_generation/owlbot/templates/poms/cloud_pom.xml.j2
  library_generation/test/resources/test-owlbot/java-admanager/ad-manager/pom-golden.xml
Labels: automerge, size: m, hermetic-build

#3131 chore: always generate a repository if not a monorepo
  library_generation/cli/entry_point.py
  library_generation/generate_pr_description.py
  library_generation/test/cli/entry_point_unit_tests.py
  library_generation/test/resources/test-config/generation_config_library_modified.yaml
Labels: automerge, size: m
