Repository googleapis/sdk-platform-java, pull requests merged in 2024-12, with the labels that each got.

#3397 chore: update action version through shell script
  hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh
  hermetic_build/library_generation/owlbot/templates/java_library/renovate.json
Labels: size: m

#3409 chore: update base image to include tag
  .cloudbuild/library_generation/library_generation.Dockerfile
Labels: size: xs

#3410 chore: update owlbot cli sha using renovate
  renovate.json
Labels: size: s

#3415 chore(hermetic-build): add hint for old commit hash error message
  hermetic_build/release_note_generation/generate_pr_description.py
Labels: size: xs

#3406 chore: merge target branch before commit changes
  .github/scripts/update_googleapis_commit.sh
  .github/workflows/update_googleapis_commit.yaml
  hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh
  hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/update_generation_config.yaml
Labels: size: s

#3438 fix: graalvm missing build time class when using protobuf 4.x
  gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
Labels: size: xs

#3441 chore(deps): Downgrade dev.cel to 0.6.0
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#3443 chore: update nightly runner
  .github/workflows/nightly.yaml
Labels: size: s

#3405 ci: Add Downstream Protobuf-Java Source Compatibility Test
  .github/workflows/downstream_protobuf_compatibility_check_nightly.yaml
  .kokoro/nightly/downstream-protobuf-source-compatibility.sh
Labels: size: m

#3455 chore: push current branch to remote
  .github/scripts/update_googleapis_commit.sh
  hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh
Labels: size: s

#3457 chore: close repo after use
  hermetic_build/common/model/config_change.py
Labels: size: xs

#3463 ci: Allow manual invocations for the Protobuf Source CI Job
  .github/workflows/downstream_protobuf_compatibility_check_nightly.yaml
Labels: size: s

#3474 chore: create a new Dockerfile
  .cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml
  .cloudbuild/library_generation/library_generation_airlock.Dockerfile
Labels: size: m

#3268 chore: group error prone dependencies for renovate.
  renovate.json
Labels: size: xs

#3472 chore: migrate library generation IT to cloud build
  .cloudbuild/library_generation/cloudbuild-library-generation-integration-test.yaml
  .cloudbuild/library_generation/scripts/__init__.py
  .cloudbuild/library_generation/scripts/integration_tests.py
  .cloudbuild/library_generation/scripts/requirements.in
  .cloudbuild/library_generation/scripts/requirements.txt
  hermetic_build/library_generation/generate_repo.py
Labels: size: l

#3477 chore: make library generation IT non-required
  .github/sync-repo-settings.yaml
Labels: size: xs

#3476 chore: remove library generation IT on workflow
  .github/workflows/verify_library_generation.yaml
  hermetic_build/library_generation/tests/compare_poms.py
  hermetic_build/library_generation/tests/integration_tests.py
  hermetic_build/library_generation/tests/resources/integration/test_generator_coordinates
Labels: size: l

#3478 chore: make library generation integration test required
  .github/sync-repo-settings.yaml
Labels: size: xs

#3479 chore: publish to two repos
  .cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml
  .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
  .github/release-please.yml
  release-please-config.json
Labels: size: m

#3480 docs: update development guide
  hermetic_build/DEVELOPMENT.md
Labels: size: s
