Repository googleapis/sdk-platform-java, pull requests merged in 2024-11, with the labels that each got.

#3331 docs: modify hermetic build docs
  hermetic_build/DEVELOPMENT.md
  hermetic_build/README.md
  hermetic_build/library_generation/DEVELOPMENT.md
  hermetic_build/release_note_generation/cli/generate_release_note.py
Labels: size: l

#3323 feat: enable selective generation based on service config include list
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java
  gapic-generator-java/src/test/proto/selective_api_generation.proto
  gapic-generator-java/src/test/resources/selective_api_generation_v1beta1.yaml
Labels: size: l

#3335 fix: Fix flaky test ScheduledRetryingExecutorTest.testCancelOuterFutureAfterStart
  gax-java/gax/src/test/java/com/google/api/gax/retrying/ScheduledRetryingExecutorTest.java
Labels: size: s

#3336 chore: update current version in trigger
  .cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml
  release-please-config.json
Labels: size: xs

#3337 docs(hermetic-build): indicate usage of Docker Buildkit in development guide
  hermetic_build/DEVELOPMENT.md
Labels: size: s

#3342 chore: add options.logging in cloud build trigger configs
  .cloudbuild/graalvm/cloudbuild-test-a-downstream-kms.yaml
  .cloudbuild/graalvm/cloudbuild-test-a-downstream-kmsinventory.yaml
  .cloudbuild/graalvm/cloudbuild-test-a.yaml
  .cloudbuild/graalvm/cloudbuild-test-b-downstream-kms.yaml
  .cloudbuild/graalvm/cloudbuild-test-b-downstream-kmsinventory.yaml
  .cloudbuild/graalvm/cloudbuild-test-b.yaml
  .cloudbuild/graalvm/cloudbuild.yaml
Labels: size: s

#3341 chore: randomize temp output directory
  hermetic_build/library_generation/generate_library.sh
Labels: size: xs

#3338 fix: use BuildKit instead of legacy builder to build the Hermetic Build images
  .cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml
  .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
  hermetic_build/DEVELOPMENT.md
  hermetic_build/library_generation/tests/integration_tests.py
Labels: size: xs

#3356 docs: fix list num
  hermetic_build/DEVELOPMENT.md
Labels: size: s

#3365 fix: instantiate GaxProperties at build time to ensure we get the protobuf version
  gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
Labels: size: xs

#3349 chore: use java-graalvm-ci-prod gcp project for running tests
  .cloudbuild/graalvm/cloudbuild-test-a-downstream-kms.yaml
  .cloudbuild/graalvm/cloudbuild-test-a-downstream-kmsinventory.yaml
  .cloudbuild/graalvm/cloudbuild-test-b-downstream-kms.yaml
  .cloudbuild/graalvm/cloudbuild-test-b-downstream-kmsinventory.yaml
Labels: size: xs

#3374 chore: explicitly specify maven central location for renovate-bot version lookups
  renovate.json
Labels: size: xs

#3326 feat: Add experimental S2A integration in client libraries grpc transport
  WORKSPACE
  gax-java/dependencies.properties
  gax-java/gax-grpc/BUILD.bazel
  gax-java/gax-grpc/pom.xml
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcLongRunningTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/testing/LocalChannelProvider.java
  gax-java/gax-grpc/src/test/resources/README.md
  gax-java/gax-grpc/src/test/resources/client_cert.pem
  gax-java/gax-grpc/src/test/resources/client_key.pem
  gax-java/gax-grpc/src/test/resources/root_cert.pem
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/InstantiatingHttpJsonChannelProvider.java
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/FixedTransportChannelProvider.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/TransportChannelProvider.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
Labels: size: l

#3375 chore: replace graalvm cloud-devrel-kokoro-resources with java-graalvm-ci-prod checks as required
  .github/sync-repo-settings.yaml
Labels: size: xs

#3330 feat: introduce `java.time` to java-core
  java-core/google-cloud-core/clirr-ignored-differences.xml
  java-core/google-cloud-core/src/main/java/com/google/cloud/RetryOption.java
  java-core/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
  java-core/google-cloud-core/src/main/java/com/google/cloud/Timestamp.java
  java-core/google-cloud-core/src/main/java/com/google/cloud/testing/BaseEmulatorHelper.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/RetryOptionTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/SerializationTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/TimestampTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/testing/BaseEmulatorHelperTest.java
Labels: size: l

#3379 fix: return all library names if repo-level parameter changes
  hermetic_build/common/cli/get_changed_libraries.py
  hermetic_build/common/model/config_change.py
  hermetic_build/common/tests/model/config_change_unit_tests.py
Labels: size: s

#3383 chore: remove maven latest version
  hermetic_build/library_generation/owlbot/synthtool/languages/java.py
  hermetic_build/library_generation/owlbot/templates/java_library/samples/install-without-bom/pom.xml
  hermetic_build/library_generation/owlbot/templates/java_library/samples/snapshot/pom.xml
  hermetic_build/library_generation/owlbot/templates/java_library/samples/snippets/pom.xml
  hermetic_build/library_generation/requirements.in
  hermetic_build/library_generation/requirements.txt
  hermetic_build/library_generation/tests/integration_tests.py
  hermetic_build/library_generation/tests/owlbot/java_unit_tests.py
  hermetic_build/library_generation/tests/resources/integration/google-cloud-java/current_generation_config.yaml
  hermetic_build/library_generation/tests/resources/integration/google-cloud-java/generation_config.yaml
Labels: size: m

#3384 chore: restrict internet access when running docker container in integration test
  hermetic_build/library_generation/tests/integration_tests.py
Labels: size: xs

#3388 docs: explain default generation config in `README.md`
  hermetic_build/README.md
  hermetic_build/library_generation/cli/entry_point.py
Labels: size: m

#3391 docs: hermetic build README syntax fix
  hermetic_build/README.md
Labels: size: xs

#3396 chore: Release Please anontations for dependencies.properties
  gax-java/dependencies.properties
Labels: size: xs

#3390 chore: remove protoc grpc from generation config
  .cloudbuild/library_generation/library_generation.Dockerfile
  hermetic_build/DEVELOPMENT.md
  hermetic_build/README.md
  hermetic_build/common/model/generation_config.py
  hermetic_build/common/tests/model/config_change_unit_tests.py
  hermetic_build/common/tests/model/generation_config_unit_tests.py
  hermetic_build/common/tests/resources/test-config/generation_config.yaml
  hermetic_build/common/tests/utils/generation_config_comparator_unit_tests.py
  hermetic_build/library_generation/generate_composed_library.py
  hermetic_build/library_generation/generate_library.sh
  hermetic_build/library_generation/tests/generate_library_unit_tests.py
  hermetic_build/library_generation/tests/generate_library_unit_tests.sh
  hermetic_build/library_generation/tests/utilities_unit_tests.py
  hermetic_build/library_generation/utils/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: l, hermetic-build

#3366 chore: Stop running Maven commands in multi treads in nightly CI
  .github/workflows/nightly.yaml
Labels: size: xs

#3398 chore: reverting Release Please anontations for dependencies.properties
  gax-java/dependencies.properties
Labels: size: xs
