Repository googleapis/sdk-platform-java, pull requests merged in 2024-06, with the labels that each got.

#2864 chore: Build all modules of sdk-platform-java in hermetic generation workflow.
  .github/workflows/hermetic_library_generation.yaml
Labels: size: xs

#2865 fix: Expose Gax meter name
  gax-java/gax/src/main/java/com/google/api/gax/tracing/OpenTelemetryMetricsRecorder.java
Labels: size: xs

#2841 feat: generate pr description from configuration comparison result
  .github/workflows/hermetic_library_generation.yaml
  library_generation/cli/entry_point.py
  library_generation/generate_pr_description.py
  library_generation/model/generation_config.py
  library_generation/test/generate_pr_description_unit_tests.py
  library_generation/test/resources/goldens/pr_description-golden.txt
  library_generation/test/utils/commit_message_formatter_unit_tests.py
  library_generation/utils/commit_message_formatter.py
Labels: size: l

#2460 feat: gapic-generator-java to perform a no-op when no services are detected
  gapic-generator-java/src/main/java/com/google/api/generator/Main.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/ClientLibraryPackageInfoComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/Composer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/GapicContext.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protowriter/Writer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/ClientLibraryPackageInfoComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/ComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protowriter/WriterTest.java
Labels: size: l

#2874 fix: Move the logic of getting systemProductName from static block to static method
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
Labels: size: s

#2878 chore: initiate library generation if Dockerfile is changed
  .github/scripts/hermetic_library_generation.sh
  .github/workflows/hermetic_library_generation.yaml
Labels: size: s

#2884 chore: add HW repo templates
  library_generation/owlbot/templates/java_library/.github/CODEOWNERS
  library_generation/owlbot/templates/java_library/.github/ISSUE_TEMPLATE/bug_report.md
  library_generation/owlbot/templates/java_library/.github/ISSUE_TEMPLATE/feature_request.md
  library_generation/owlbot/templates/java_library/.github/ISSUE_TEMPLATE/support_request.md
  library_generation/owlbot/templates/java_library/.github/PULL_REQUEST_TEMPLATE.md
  library_generation/owlbot/templates/java_library/.github/auto-label.yaml
  library_generation/owlbot/templates/java_library/.github/blunderbuss.yml
  library_generation/owlbot/templates/java_library/.github/dependabot.yml
  library_generation/owlbot/templates/java_library/.github/generated-files-bot.yml
  library_generation/owlbot/templates/java_library/.github/release-please.yml
  library_generation/owlbot/templates/java_library/.github/release-trigger.yml
  library_generation/owlbot/templates/java_library/.github/snippet-bot.yml
  library_generation/owlbot/templates/java_library/.github/sync-repo-settings.yaml
  library_generation/owlbot/templates/java_library/.github/workflows/approve-readme.yaml
  library_generation/owlbot/templates/java_library/.github/workflows/ci.yaml
  library_generation/owlbot/templates/java_library/.github/workflows/renovate_config_check.yaml
  library_generation/owlbot/templates/java_library/.github/workflows/samples.yaml
  library_generation/owlbot/templates/java_library/.kokoro/build.sh
  library_generation/owlbot/templates/java_library/.kokoro/common.cfg
  library_generation/owlbot/templates/java_library/.kokoro/continuous.cfg
  library_generation/owlbot/templates/java_library/.kokoro/presubmit.cfg
  library_generation/owlbot/templates/java_library/.kokoro/trampoline.sh
Labels: size: l

#2888 feat: push SNAPSHOT versions of the hermetic build docker image
  .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
  .cloudbuild/library_generation/cloudbuild-library-generation-release.yaml
Labels: hermetic-build

#2923 chore: adjust repo-metadata generation to fit existing files in HW repos
  library_generation/generate_composed_library.py
  library_generation/model/generation_config.py
  library_generation/model/library_config.py
  library_generation/test/resources/goldens/.repo-metadata-monorepo-golden.json
  library_generation/test/resources/goldens/.repo-metadata-non-monorepo-golden.json
  library_generation/test/resources/goldens/.repo-metadata-proto-only-golden.json
  library_generation/test/utilities_unit_tests.py
  library_generation/utils/utilities.py
Labels: size: m

#2890 feat: populate `.repo-metadata.json` from highest version
  library_generation/generate_composed_library.py
  library_generation/model/gapic_config.py
  library_generation/model/library_config.py
  library_generation/test/model/gapic_config_unit_tests.py
  library_generation/test/model/library_config_unit_tests.py
Labels: size: m

#2885 chore: add hermetic build templates for HW libs
  library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh
  library_generation/owlbot/templates/java_library/.github/workflows/update_generation_config.yaml
Labels: size: m

#2932 chore: add iam logging
  java-iam/.OwlBot-hermetic.yaml
  java-iam/.repo-metadata.json
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/logging/AuditData.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/logging/AuditDataOrBuilder.java
  java-iam/proto-google-iam-v1/src/main/java/com/google/iam/v1/logging/AuditDataProto.java
  java-iam/proto-google-iam-v1/src/main/proto/google/iam/v1/logging/audit_data.proto
  java-iam/proto-google-iam-v1/src/main/proto/google/iam/v1/options.proto
  java-iam/proto-google-iam-v1/src/main/proto/google/iam/v1/policy.proto
  library_generation/generate_library.sh
Labels: size: l

#2952 fix: restore hermetic build image publication
  .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
  release-please-config.json
Labels: size: xs

#2955 chore: trigger build via development guide fix
  library_generation/DEVELOPMENT.md
Labels: size: xs

#2954 chore: restore hermetic image tag to current SNAPSHOT
  .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
Labels: size: xs

#2937 feat: parse `BUILD.bzel` to determine whether a commit that only changed `BUILD.bazel` is a qualified commit
  library_generation/model/config_change.py
  library_generation/model/gapic_inputs.py
  library_generation/test/model/config_change_unit_tests.py
Labels: size: m

#2959 chore: update plugin version in template
  library_generation/templates/root-pom.xml.j2
  library_generation/test/resources/test_monorepo_postprocessing/pom-golden.xml
Labels: size: xs
