Repository googleapis/sdk-platform-java, pull requests merged in 2024-07, with the labels that each got.

#2993 chore: Use argLine maven property
  gax-java/gax/pom.xml
Labels: size: xs

#3010 chore: Fix flaky InstantiatingGrpcChannelProviderTest on Mac
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: size: xs

#3012 chore: use sha256 in hashing
  library_generation/model/library_config.py
Labels: size: xs

#3007 feat: get released version from versions.txt to render `README.md`
  .cloudbuild/library_generation/library_generation.Dockerfile
  library_generation/generate_composed_library.py
  library_generation/generate_repo.py
  library_generation/model/library_config.py
  library_generation/model/repo_config.py
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/owlbot/templates/java_library/README.md
  library_generation/postprocess_library.sh
  library_generation/templates/owlbot.yaml.monorepo.j2
  library_generation/test/model/library_config_unit_tests.py
  library_generation/test/model/repo_config_unit_tests.py
  library_generation/utils/utilities.py
Labels: size: l

#3016 fix: `BaseApiTracer` to noop on attemptFailed via overloaded method call
  gax-java/gax/src/main/java/com/google/api/gax/tracing/BaseApiTracer.java
Labels: size: xs

#3011 chore: transfer java-related synthtool code into the library_generation image
  .cloudbuild/library_generation/library_generation.Dockerfile
  .github/snippet-bot.yml
  library_generation/owlbot/synthtool/__init__.py
  library_generation/owlbot/synthtool/_tracked_paths.py
  library_generation/owlbot/synthtool/gcp/common.py
  library_generation/owlbot/synthtool/gcp/samples.py
  library_generation/owlbot/synthtool/gcp/snippets.py
  library_generation/owlbot/synthtool/languages/java.py
  library_generation/owlbot/synthtool/sources/templates.py
  library_generation/owlbot/synthtool/transforms.py
  library_generation/requirements.in
  library_generation/requirements.txt
  library_generation/setup.py
Labels: size: xl

#3018 deps: Use Gapic-Showcase v0.35.1
  showcase/gapic-showcase/pom.xml
Labels: size: xs

#2965 chore: revert disable renovate for grpc and guava versions
  renovate.json
Labels: size: xs

#3025 chore: Revert disable renovate for protobuf dependencies
  renovate.json
Labels: size: xs

#3037 chore: move the `attemptFailed` logic from BaseApiTracer to ApiTracer
  gax-java/gax/src/main/java/com/google/api/gax/tracing/ApiTracer.java
  gax-java/gax/src/main/java/com/google/api/gax/tracing/BaseApiTracer.java
Labels: do not merge, size: s

#3038 chore: renovate bot should ignore requirement.txt
  renovate.json
Labels: size: xs

#3026 chore: remove CODEOWNERS to avoid tagging everyone for review
  .github/CODEOWNERS
Labels: size: xs

#3036 Chore: add CEL and Tink to shared dependencies.
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: s

#2347 feat: Mark `getDefaultEndpoint()` with @ObsoleteApi
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/ApiVersionTestingStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingServiceV2StubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/PublisherStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/WickedStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/ComplianceStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonApiVersionTestingStubSettings.golden
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/ComplianceStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/EchoStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/IdentityStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/MessagingStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/SequenceServiceStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/TestingStubSettings.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/ConnectionServiceStubSettings.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/TetherStubSettings.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  test/integration/goldens/bigtable/src/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/AddressesStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/RegionOperationsStubSettings.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java
  test/integration/goldens/iam/src/com/google/iam/v1/stub/IAMPolicyStubSettings.java
  test/integration/goldens/kms/src/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/stub/LibraryServiceStubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  test/integration/goldens/storage/src/com/google/storage/v2/stub/StorageStubSettings.java
Labels: size: m

#3055 docs: add support option to 'new issue' choices
  .github/ISSUE_TEMPLATE/config.yml
Labels: size: xs

#3052 feat: add `transport` option to `generation_config.yaml`
  library_generation/README.md
  library_generation/generate_composed_library.py
  library_generation/model/generation_config.py
  library_generation/model/library_config.py
  library_generation/model/repo_config.py
  library_generation/test/resources/goldens/.repo-metadata-custom-transport-golden.json
  library_generation/test/utilities_unit_tests.py
Labels: size: m

#3051 fix: Generator to skip generation for empty services.
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoEmpty.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java
  gapic-generator-java/src/test/proto/echo_grpcrest.proto
  gapic-generator-java/src/test/proto/service_with_no_methods.proto
  showcase/gapic-showcase/src/main/resources/META-INF/native-image/com.google.showcase.v1beta1/reflect-config.json
Labels: size: l

#3020 chore: Add OpenTelemetry semantic conventions to shared dependencies
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#3040 chore: make generator version an optional param
  .github/scripts/hermetic_library_generation.sh
  generation_config.yaml
  library_generation/README.md
  library_generation/model/generation_config.py
  library_generation/test/model/generation_config_unit_tests.py
  library_generation/test/resources/test-config/config_without_generator.yaml
  library_generation/test/resources/test-config/config_without_libraries_bom_version.yaml
Labels: size: m

#3045 chore: bake the grpc plugin in the hermetic library generation image
  .cloudbuild/library_generation/library_generation.Dockerfile
  library_generation/generate_library.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/utils/utilities.sh
  renovate.json
Labels: size: m

#3019 fix: improve warnings for Direct Path xDS set via env
  .github/workflows/ci.yaml
  gax-java/gax-grpc/pom.xml
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: size: m

#3073 feat: update ErrorDetails to allow unpacking arbitrary messages
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ErrorDetails.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ErrorDetailsTest.java
Labels: owlbot:ignore, size: s
