Repository googleapis/sdk-platform-java, pull requests merged in 2024-09, with the labels that each got.

#3146 chore: re-generate when config or Dockerfile is changed
  .github/scripts/hermetic_library_generation.sh
Labels: size: s

#3067 feat: bake gapic-generator-java into the hermetic build docker image
  .cloudbuild/library_generation/library_generation.Dockerfile
  .github/workflows/ci.yaml
  .gitignore
  .kokoro/presubmit/downstream-compatibility-spring.sh
  library_generation/DEVELOPMENT.md
  library_generation/gapic-generator-java-wrapper
  library_generation/generate_composed_library.py
  library_generation/generate_library.sh
  library_generation/test/generate_library_unit_tests.py
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/integration_tests.py
  library_generation/test/resources/integration/test_generator_coordinates
  library_generation/test/test_utilities.sh
  library_generation/utils/utilities.py
  library_generation/utils/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: l

#3164 fix: Remove null check for paged Protobuf messages
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingServiceV2StubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/PublisherStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoStubSettings.golden
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/ComplianceStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/EchoStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/IdentityStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/MessagingStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/SequenceServiceStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/TestingStubSettings.java
  showcase/gapic-showcase/src/main/resources/META-INF/native-image/com.google.showcase.v1beta1/reflect-config.json
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/ConnectionServiceStubSettings.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/AddressesStubSettings.java
  test/integration/goldens/kms/src/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/stub/LibraryServiceStubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  test/integration/goldens/storage/src/com/google/storage/v2/stub/StorageStubSettings.java
Labels: size: l

#3078 deps: add opentelemetry exporter-metrics and shared-resoucemapping to shared dependencies
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: s

#3141 feat: add Batcher#close(timeout) and Batcher#cancelOutstanding
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/batching/Batcher.java
  gax-java/gax/src/main/java/com/google/api/gax/batching/BatcherImpl.java
  gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: size: m

#3180 chore: Correctly closing the release please config for gapic-generator-java in library generation Dockerfile
  .cloudbuild/library_generation/library_generation.Dockerfile
Labels: size: xs

#3182 fix: generate pr description with repo level change
  library_generation/generate_pr_description.py
  library_generation/test/generate_pr_description_unit_tests.py
  library_generation/test/resources/goldens/repo_level_and_no_qualified_commit_pr_description-golden.txt
  library_generation/test/resources/goldens/repo_level_only_pr_description-golden.txt
Labels: size: m

#3171 chore: make the showcase scripts to automatically prepare the generator jar
  .github/workflows/ci.yaml
  showcase/README.md
  showcase/scripts/generate_showcase.sh
Labels: automerge: exact, size: m

#3190 chore: do not use renovate to update protobuf
  renovate.json
Labels: size: s

#3170 feat: expose property in GrpcTransportChannel if it uses direct path.
  gax-java/gax-grpc/clirr-ignored-differences.xml
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcTransportChannel.java
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcTransportChannelTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
  gax-java/gax/clirr-ignored-differences.xml
Labels: size: m

#3188 chore: Add Clirr exemptions for Protobuf 4.27.4 runtime
  library_generation/owlbot/templates/clirr/clirr-ignored-differences.xml.j2
Labels: size: m

#3197 chore: Add Clirr exemptions for Protobuf 4.27.4+ runtime
  java-common-protos/proto-google-common-protos/clirr-ignored-differences.xml
  java-iam/proto-google-iam-v1/clirr-ignored-differences.xml
  java-iam/proto-google-iam-v2/clirr-ignored-differences.xml
  java-iam/proto-google-iam-v2beta/clirr-ignored-differences.xml
Labels: size: m

#3203 chore: do not exit early if there's no code change
  .github/scripts/hermetic_library_generation.sh
Labels: size: s

#3202 feat: Metrics tracer addAttribute map overload
  gax-java/gax/src/main/java/com/google/api/gax/tracing/MetricsTracer.java
  gax-java/gax/src/test/java/com/google/api/gax/tracing/MetricsTracerTest.java
Labels: size: s

#3211 chore: Update root pom.xml template to use maven deploy v3.1.3
  library_generation/templates/root-pom.xml.j2
  library_generation/test/resources/test_monorepo_postprocessing/pom-golden.xml
Labels: size: xs

#3208 feat: generate a GAPIC library from api definition
  .github/scripts/hermetic_library_generation.sh
  library_generation/DEVELOPMENT.md
  library_generation/README.md
  library_generation/cli/entry_point.py
  library_generation/generate_composed_library.py
  library_generation/generate_repo.py
  library_generation/test/cli/entry_point_unit_tests.py
  library_generation/test/integration_tests.py
  library_generation/utils/utilities.py
Labels: size: m

#3223 chore: specify `options.logging` in cloud build
  .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
Labels: size: xs

#3227 chore: migrate java tests
  .github/workflows/verify_library_generation.yaml
  library_generation/owlbot/synthtool/__init__.py
  library_generation/owlbot/synthtool/gcp/common.py
  library_generation/owlbot/synthtool/languages/java.py
  library_generation/owlbot/templates/java_library/.github/workflows/update_generation_config.yaml
  library_generation/requirements.in
  library_generation/requirements.txt
  library_generation/test/owlbot/java_unit_tests.py
  library_generation/test/owlbot/util.py
  library_generation/test/resources/test-owlbot/fixtures/java_templates/release-please-update/.github/release-please.yml
  library_generation/test/resources/test-owlbot/fixtures/java_templates/release-please-update/.repo-metadata.json
  library_generation/test/resources/test-owlbot/fixtures/java_templates/standard/.repo-metadata.json
  library_generation/test/resources/test-owlbot/testdata/FooGrpcGolden.java
  library_generation/test/resources/test-owlbot/testdata/FooProtoGolden.java
  library_generation/test/resources/test-owlbot/testdata/SampleClass.java
  library_generation/test/resources/test-owlbot/testdata/SampleClassGolden.java
  library_generation/test/resources/test-owlbot/testdata/SampleCopyMethodGolden.java
  library_generation/test/resources/test-owlbot/testdata/SampleDeprecateClass.java
  library_generation/test/resources/test-owlbot/testdata/SampleDeprecateMethodGolden.java
  library_generation/test/resources/test-owlbot/testdata/src/foo/FooGrpc.java
  library_generation/test/resources/test-owlbot/testdata/src/foo/FooProto.java
Labels: size: xl

#3250 chore: update required check
  .github/sync-repo-settings.yaml
Labels: size: xs
