Repository googleapis/sdk-platform-java, pull requests merged in 2024-01, with the labels that each got.

#2313 feat: Full Endpoint Resolution from EndpointContext
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/testing/FakeStubSettings.java
Labels: size: l

#2326 chore: update release-please configs to include cloudbuild yaml files
  .github/release-please.yml
Labels: automerge, size: xs

#2315 feat: new artifact for sdk-platform-java configs.
  pom.xml
  sdk-platform-java-config/pom.xml
Labels: size: s

#2223 feat: unmanaged dependency check
  .github/workflows/ci.yaml
  .github/workflows/create_additional_release_tag.yaml
  java-shared-dependencies/unmanaged-dependency-check/action.yaml
  java-shared-dependencies/unmanaged-dependency-check/pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/main/java/com/google/cloud/UnmanagedDependencyCheck.java
  java-shared-dependencies/unmanaged-dependency-check/src/test/java/com/google/cloud/UnmanagedDependencyCheckTest.java
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/bigtable-pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/gax-example-pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/local-install.sh
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/nested-dependency-pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/shared-dependency-3.18.0-pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/transitive-dependency-pom.xml
Labels: size: l

#2334 chore: one time manual docker images update for shared-deps 3.21.0 release
  .cloudbuild/cloudbuild-test-a.yaml
  .cloudbuild/cloudbuild-test-b.yaml
  .cloudbuild/cloudbuild.yaml
Labels: size: xs

#2335 fix: re-enable checkstyle in sdk-platform-java-config
  sdk-platform-java-config/java.header
  sdk-platform-java-config/license-checks.xml
  sdk-platform-java-config/pom.xml
Labels: automerge, size: s

#2331 feat: Add Universe Domain to ClientSettings
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientSettings.java
Labels: size: s

#2336 build(deps): Bump Google Java Auth Library to v1.21.0
  gapic-generator-java-pom-parent/pom.xml
Labels: automerge, size: xs

#2329 feat: Add Universe Domain to Java-Core
  java-core/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/ServiceOptionsTest.java
Labels: size: l

#2341 chore: Bump java auth library for Bazel Builds
  gax-java/dependencies.properties
Labels: size: xs

#2345 ci: fix typo in additional tag job
  .github/workflows/create_additional_release_tag.yaml
Labels: automerge, size: xs

#2344 build: remove caching in java 8 setup
  .github/workflows/nightly.yaml
Labels: size: xs

#2281 fix: DirectPath non-default SA requires creds
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: automerge, size: s

#2349 chore: fix release-please-config json extra files parameter
  release-please-config.json
Labels: automerge, size: s

#2348 feat: Remove setting the default endpoint in StubSettings
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/comment/SettingsCommentComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingServiceV2StubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/PublisherStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/WickedStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/ComplianceStubSettings.golden
  gax-java/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/ComplianceStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/EchoStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/IdentityStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/MessagingStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/SequenceServiceStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/TestingStubSettings.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITEndpointContext.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITGdch.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/TestClientInitializer.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/ConnectionServiceStubSettings.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/TetherStubSettings.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  test/integration/goldens/bigtable/src/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/AddressesStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/RegionOperationsStubSettings.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java
  test/integration/goldens/iam/src/com/google/iam/v1/stub/IAMPolicyStubSettings.java
  test/integration/goldens/kms/src/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/stub/LibraryServiceStubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  test/integration/goldens/storage/src/com/google/storage/v2/stub/StorageStubSettings.java
Labels: size: l

#2351 fix: adjust release-please configs for cloudbuild yaml updates
  release-please-config.json
Labels: size: s

#2357 chore: remove unused files
  java-common-protos/.github/CODEOWNERS
  java-common-protos/.github/ISSUE_TEMPLATE/bug_report.md
  java-common-protos/.github/ISSUE_TEMPLATE/feature_request.md
  java-common-protos/.github/ISSUE_TEMPLATE/support_request.md
  java-common-protos/.github/PULL_REQUEST_TEMPLATE.md
  java-common-protos/.github/auto-label.yaml
  java-common-protos/.github/blunderbuss.yml
  java-common-protos/.github/generated-files-bot.yml
  java-common-protos/.github/release-please.yml
  java-common-protos/.github/release-trigger.yml
  java-common-protos/.github/snippet-bot.yml
  java-common-protos/.github/sync-repo-settings.yaml
  java-common-protos/.github/trusted-contribution.yml
  java-common-protos/.github/workflows/approve-readme.yaml
  java-common-protos/.github/workflows/ci.yaml
  java-common-protos/.gitignore
  java-common-protos/CODE_OF_CONDUCT.md
  java-common-protos/CONTRIBUTING.md
  java-common-protos/LICENSE
  java-common-protos/SECURITY.md
  java-common-protos/java.header
  java-common-protos/license-checks.xml
  java-common-protos/owlbot.py
  java-common-protos/renovate.json
  java-iam/.gitignore
  java-iam/LICENSE
  java-iam/SECURITY.md
  java-iam/java.header
  java-iam/license-checks.xml
Labels: size: xl

#2337 test: Add a sample generate_config yaml file.
  library_generation/test/resources/integration/google-cloud-java/generation_config.yaml
Labels: size: m

#2330 feat: Validate the Universe Domain
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallContext.java
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcClientCalls.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/ChannelPoolTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcCallContextTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcCallableFactoryTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcClientCallsTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectServerStreamingCallableTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectStreamingCallableTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcLongRunningTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcResponseMetadataTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonCallContext.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCalls.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonClientCallsTest.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonClientInterceptorTest.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectCallableTest.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ApiCallContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/testing/FakeCallContext.java
Labels: size: l

#2354 deps: update gapic-showcase to v0.30.0
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/TestingClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/package-info.java
  showcase/gapic-showcase/src/main/resources/META-INF/native-image/com.google.showcase.v1beta1/reflect-config.json
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/TestingGrpc.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoOuterClass.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoRequestOrBuilder.java
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/echo.proto
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/testing.proto
Labels: size: l

#2369 build(deps): Bump Google Java Auth Library to v1.22.0
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
Labels: size: xs

#2372 chore: change regex in check
  java-shared-dependencies/unmanaged-dependency-check/src/main/java/com/google/cloud/UnmanagedDependencyCheck.java
Labels: size: xs

#2374 chore: Update renovate.json
  renovate.json
Labels: size: xs

#2377 chore: add custom artifacts
  java-shared-dependencies/unmanaged-dependency-check/src/main/java/com/google/cloud/UnmanagedDependencyCheck.java
  java-shared-dependencies/unmanaged-dependency-check/src/test/java/com/google/cloud/UnmanagedDependencyCheckTest.java
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/bigtable-pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/google-internal-artifact-test-case-pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/local-install.sh
Labels: size: m

#2401 chore: fix workflow of create additional release tags
  .github/workflows/create_additional_release_tag.yaml
Labels: size: xs

#2402 chore: add artifacts in gapic bom in allow list
  java-shared-dependencies/unmanaged-dependency-check/src/main/java/com/google/cloud/UnmanagedDependencyCheck.java
  java-shared-dependencies/unmanaged-dependency-check/src/test/java/com/google/cloud/UnmanagedDependencyCheckTest.java
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/google-internal-artifact-test-case-pom.xml
Labels: size: s

#2407 chore: fix go link for unmanaged dependency check
  java-shared-dependencies/unmanaged-dependency-check/action.yaml
Labels: automerge, size: xs

#2403 feat: Introduce interfaces for metrics instrumentation
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallContext.java
  gax-java/gax/src/main/java/com/google/api/gax/tracing/ApiTracer.java
  gax-java/gax/src/main/java/com/google/api/gax/tracing/BaseApiTracer.java
  gax-java/gax/src/main/java/com/google/api/gax/tracing/MethodName.java
  gax-java/gax/src/main/java/com/google/api/gax/tracing/MetricsRecorder.java
  gax-java/gax/src/main/java/com/google/api/gax/tracing/MetricsTracer.java
  gax-java/gax/src/main/java/com/google/api/gax/tracing/MetricsTracerFactory.java
  java-core/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
Labels: size: l

#2410 chore: do not include optional dependencies in unmanaged dependency c…
  java-shared-dependencies/unmanaged-dependency-check/src/main/java/com/google/cloud/UnmanagedDependencyCheck.java
  java-shared-dependencies/unmanaged-dependency-check/src/test/java/com/google/cloud/UnmanagedDependencyCheckTest.java
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/google-internal-artifact-test-case-pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/local-install.sh
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/shared-dependency-3.18.0-pom.xml
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/shared-dependency-pom.xml
Labels: size: m

#2412 fix: Verify Universe Domain's DirectPath Compatibility after Endpoint Resolution
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: size: s

#2414 chore: add `google/shopping/type/types.proto` when generating shopping APIs
  library_generation/generate_library.sh
Labels: size: xs

#2333 feat: move new client script
  .gitignore
  library_generation/new_client/client_inputs.py
  library_generation/new_client/get_generator_version_from_workspace.sh
  library_generation/new_client/new-client.py
  library_generation/new_client/requirements.in
  library_generation/new_client/requirements.txt
  library_generation/new_client/templates.py
  library_generation/new_client/templates/owlbot.py.j2
  library_generation/new_client/templates/owlbot.yaml.monorepo.j2
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/owlbot/bin/format_source.sh
  library_generation/owlbot/src/fix-poms.py
  library_generation/owlbot/templates/poms/bom_pom.xml.j2
  library_generation/owlbot/templates/poms/cloud_pom.xml.j2
  library_generation/owlbot/templates/poms/grpc_pom.xml.j2
  library_generation/owlbot/templates/poms/parent_pom.xml.j2
  library_generation/owlbot/templates/poms/proto_pom.xml.j2
  library_generation/postprocess_library.sh
  library_generation/repo-level-postprocess/generate_gapic_bom.sh
  library_generation/repo-level-postprocess/generate_root_pom.sh
Labels: size: xl

#2426 ci: validate unmanaged dependency check in a few downstream repositories
  .github/workflows/downstream_unmanaged_dependency_check.yaml
Labels: size: m

#2424 ci: suppress download progress in unmanaged dependency check
  java-shared-dependencies/unmanaged-dependency-check/src/test/resources/local-install.sh
Labels: size: s

#2342 feat: enable generation with postprocessing of multiple service versions
  .github/workflows/verify_library_generation.yaml
  library_generation/.gitignore
  library_generation/generate_composed_library.py
  library_generation/generate_library.sh
  library_generation/main.py
  library_generation/model/ClientInputs.py
  library_generation/model/GapicConfig.py
  library_generation/model/GenerationConfig.py
  library_generation/model/Library.py
  library_generation/model/LibraryConfig.py
  library_generation/new_client/new-client.py
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/postprocess_library.sh
  library_generation/requirements.in
  library_generation/test/__init__.py
  library_generation/test/compare_poms.py
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/resources/integration/google-cloud-java/generation_config.yaml
  library_generation/test/resources/integration/java-bigtable/generation_config.yaml
  library_generation/test/resources/misc/BUILD_gapic_yaml.bazel
  library_generation/test/resources/misc/BUILD_no_gapic_yaml.bazel
  library_generation/test/resources/misc/BUILD_no_service_config.bazel
  library_generation/test/resources/misc/BUILD_no_service_yaml.bazel
  library_generation/test/resources/misc/BUILD_service_config.bazel
  library_generation/test/resources/misc/BUILD_service_yaml.bazel
  library_generation/test/resources/proto_path_list.txt
  library_generation/test/test_utilities.sh
  library_generation/test/unit_tests.py
  library_generation/utilities.py
  library_generation/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: xl

#2421 feat: MetricsTracer implementation
  gax-java/gax/src/main/java/com/google/api/gax/tracing/MetricsTracer.java
  gax-java/gax/src/test/java/com/google/api/gax/tracing/MetricsTracerFactoryTest.java
  gax-java/gax/src/test/java/com/google/api/gax/tracing/MetricsTracerTest.java
Labels: size: l

#2430 fix: Move direct path misconfiguration log to before creating the first channel
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: automerge, size: s
