Repository googleapis/sdk-platform-java, pull requests merged in 2024-04, with the labels that each got.

#2604 feat: add config change
  library_generation/generate_composed_library.py
  library_generation/generate_library.sh
  library_generation/generate_pr_description.py
  library_generation/generate_repo.py
  library_generation/model/config_change.py
  library_generation/model/generation_config.py
  library_generation/postprocess_library.sh
  library_generation/setup.py
  library_generation/test/compare_poms.py
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/integration_tests.py
  library_generation/test/model/config_change_unit_tests.py
  library_generation/test/model/generation_config_unit_test.py
  library_generation/test/utilities_unit_tests.py
  library_generation/test/utils/generation_config_comparator_unit_tests.py
  library_generation/test/utils/proto_path_utils_unit_tests.py
  library_generation/utils/__init__.py
  library_generation/utils/generation_config_comparator.py
  library_generation/utils/proto_path_utils.py
  library_generation/utils/utilities.py
  library_generation/utils/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: l

#2440 feat: Client/StubSettings' getEndpoint() returns the resolved endpoint
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/comment/SettingsCommentComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingServiceV2StubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/PublisherStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/WickedStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/ComplianceStubSettings.golden
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallContext.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonCallContext.java
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientSettingsTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/testing/FakeCallContext.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/ComplianceStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/EchoStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/IdentityStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/MessagingStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/SequenceServiceStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/TestingStubSettings.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITEndpointContext.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/TestClientInitializer.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/ConnectionServiceStubSettings.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/TetherStubSettings.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  test/integration/goldens/bigtable/src/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/AddressesStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/RegionOperationsStubSettings.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java
  test/integration/goldens/iam/src/com/google/iam/v1/stub/IAMPolicyStubSettings.java
  test/integration/goldens/kms/src/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/stub/LibraryServiceStubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  test/integration/goldens/storage/src/com/google/storage/v2/stub/StorageStubSettings.java
Labels: size: xl

#2612 feat: Add ChannelPoolSettings Getter for gRPC's ChannelProvider
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
Labels: size: xs

#2613 chore: add integration test running in docker container
  .cloudbuild/library_generation/cloudbuild-test-library-generation.yaml
  .github/workflows/verify_library_generation.yaml
  library_generation/test/container_integration_tests.sh
  library_generation/test/integration_tests.py
Labels: size: l

#2616 feat: add entry point
  library_generation/README.md
  library_generation/cli/entry_point.py
  library_generation/generate_pr_description.py
  library_generation/generate_repo.py
  library_generation/model/config_change.py
  library_generation/test/cli/__init__.py
  library_generation/test/cli/entry_point_unit_tests.py
  library_generation/test/generate_pr_description_unit_tests.py
  library_generation/test/integration_tests.py
  library_generation/test/model/config_change_unit_tests.py
  library_generation/test/resources/integration/google-cloud-java/baseline_generation_config.yaml
  library_generation/test/resources/integration/google-cloud-java/current_generation_config.yaml
  library_generation/test/utils/generation_config_comparator_unit_tests.py
  library_generation/utils/generation_config_comparator.py
Labels: size: l

#2619 refactor: Rename requirements.in to requirements.txt.
  .cloudbuild/library_generation/library_generation.Dockerfile
  .github/workflows/verify_library_generation.yaml
  library_generation/README.md
  library_generation/requirements.txt
Labels: automerge, size: s

#2626 chore: remove tag of unmanaged dependency check
  .github/workflows/create_additional_release_tag.yaml
Labels: size: s

#2462 chore: get package info from deps.dev
  .github/workflows/anaylze_dependency.yaml
  .github/workflows/ci.yaml
  java-shared-dependencies/dependency-analyzer/pom.xml
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/DependencyAnalyzer.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/external/DepsDevClient.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Advisory.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AdvisoryKey.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AnalysisResult.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/DependencyResponse.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/License.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/LicenseCategory.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Node.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/PackageInfo.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/PkgManagement.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/QueryResult.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Relation.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/ReportResult.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Result.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Version.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/VersionKey.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/external/DepsDevClientTest.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/AnalysisResultTest.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/LicenseTest.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/VersionKeyTest.java
Labels: size: xl

#2634 chore: remove `is_monorepo` and `path_to_yaml` from `GenerationConfig`
  library_generation/cli/entry_point.py
  library_generation/generate_composed_library.py
  library_generation/generate_pr_description.py
  library_generation/generate_repo.py
  library_generation/model/generation_config.py
  library_generation/test/generate_repo_unit_tests.py
  library_generation/test/integration_tests.py
  library_generation/test/model/config_change_unit_tests.py
  library_generation/test/model/generation_config_unit_test.py
  library_generation/test/utilities_unit_tests.py
  library_generation/test/utils/generation_config_comparator_unit_tests.py
  library_generation/utils/utilities.py
Labels: size: m

#2592 feat: Validate the Universe Domain inside Java-Core
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  java-core/google-cloud-core-http/src/main/java/com/google/cloud/http/HttpTransportOptions.java
  java-core/google-cloud-core-http/src/test/java/com/google/cloud/http/HttpTransportOptionsTest.java
Labels: size: l

#2638 chore: change variable name
  library_generation/README.md
  library_generation/cli/entry_point.py
  library_generation/test/cli/entry_point_unit_tests.py
  library_generation/test/integration_tests.py
  library_generation/test/utils/generation_config_comparator_unit_tests.py
Labels: size: m

#2642 chore: Change all the references of OwlBot.yaml to OwlBot-hermetic.yaml.
  .gitignore
  library_generation/README.md
  library_generation/generate_composed_library.py
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/postprocess_library.sh
  library_generation/test/resources/goldens/.OwlBot-hermetic-golden.yaml
  library_generation/test/resources/integration/google-cloud-java/current_generation_config.yaml
  library_generation/test/utilities_unit_tests.py
  library_generation/utils/utilities.py
  library_generation/utils/utilities.sh
Labels: size: m

#2575 chore: add opentelemery gRPC instrumentation to shared dependencies.
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#2645 chore: do not generate pr description if two commits are same
  library_generation/generate_pr_description.py
  library_generation/test/generate_pr_description_unit_tests.py
Labels: size: s

#2636 fix: remove duplicated calls to AutoValue builders
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java
Labels: size: xs

#2618 chore: disable renovate for grpc and guava versions
  renovate.json
Labels: size: xs

#2629 chore: remove old native image kokoro downstream jobs
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/graalvm-native-17-downstream.cfg
  .kokoro/presubmit/graalvm-native-downstream.cfg
Labels: size: s

#2628 fix: remove unnecessary slf4j and AbstractGoogleClientRequest native image configs
  gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
Labels: size: xs

#2664 chore: shared-deps third party's parent is generator-pom-parent
  gapic-generator-java-pom-parent/pom.xml
  gax-java/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: s

#2666 chore: disable renovate for protobuf dependencies
  renovate.json
Labels: size: xs

#2644 chore: remove generated files in tests
  .gitignore
  library_generation/generate_repo.py
  library_generation/test/compare_poms.py
  library_generation/test/integration_tests.py
  library_generation/test/utilities_unit_tests.py
  library_generation/test/utils/monorepo_postprocessor_unit_tests.py
Labels: size: m

#2668 chore: use record in dependency analyzer
  .github/workflows/ci.yaml
  java-shared-dependencies/dependency-analyzer/pom.xml
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/DependencyAnalyzer.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/external/DepsDevClient.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Advisory.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AdvisoryKey.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AnalysisResult.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/DependencyResponse.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Node.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/PackageInfo.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/QueryResult.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Result.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Version.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/VersionKey.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/external/DepsDevClientTest.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/AnalysisResultTest.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/VersionKeyTest.java
Labels: size: l

#2673 chore: Remove unused Python protobuf dependencies from requirements.txt
  library_generation/requirements.txt
Labels: automerge, size: xs

#2637 fix: replace `cfg = "host"` with `cfg = "exec"`
  gax-java/gax_java.bzl
  rules_java_gapic/java_gapic.bzl
Labels: automerge, size: xs

#2653 deps: update gapic-showcase to v0.33.0
  WORKSPACE
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoClient.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/package-info.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/GrpcEchoStub.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonEchoStub.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoOuterClass.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoRequest.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoRequestOrBuilder.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoResponse.java
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoResponseOrBuilder.java
  showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/echo.proto
Labels: size: l

#2681 deps: Make opentelemetry-api an optional dependency.
  gax-java/gax/pom.xml
Labels: size: xs

#2682 docs: Add contributing guidelines to PR and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size: s

#2684 chore: show difference in integration test
  library_generation/test/integration_tests.py
Labels: size: s

#2674 chore: update package information report
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/DependencyAnalyzer.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/external/DepsDevClient.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AnalysisResult.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/License.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/LicenseCategory.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/VersionKey.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/external/DepsDevClientTest.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/AnalysisResultTest.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/LicenseTest.java
Labels: size: m

#2630 feat: Parser to consume the api-versioning value from proto
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/Composer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceSettingsClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/GapicClass.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/Service.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/ComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceClientClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/model/ServiceTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java
  gapic-generator-java/src/test/proto/api_version_testing.proto
Labels: size: l

#2678 chore: Add `load()`s for the Bazel builtin java rules
  gax-java/gax_java.bzl
Labels: size: xs

#2689 chore: change report logic
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/DependencyAnalyzer.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Advisory.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AnalysisResult.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/License.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/PackageInfo.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/AnalysisResultTest.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/LicenseTest.java
Labels: size: m

#2686 chore: change protobuf_version to protoc_version
  library_generation/README.md
  library_generation/generate_composed_library.py
  library_generation/generate_library.sh
  library_generation/model/generation_config.py
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/generate_pr_description_unit_tests.py
  library_generation/test/model/config_change_unit_tests.py
  library_generation/test/model/generation_config_unit_test.py
  library_generation/test/resources/integration/google-cloud-java/baseline_generation_config.yaml
  library_generation/test/resources/integration/google-cloud-java/current_generation_config.yaml
  library_generation/test/resources/integration/java-bigtable/generation_config.yaml
  library_generation/test/resources/test-config/generation_config.yaml
  library_generation/test/utils/generation_config_comparator_unit_tests.py
  library_generation/utils/utilities.sh
Labels: size: m

#2692 chore: fix confusing step name
  .github/workflows/nightly.yaml
Labels: size: xs

#2691 feat: add a CLI tool to validate generation configuration
  library_generation/cli/entry_point.py
  library_generation/model/generation_config.py
  library_generation/test/cli/entry_point_unit_tests.py
  library_generation/test/model/generation_config_unit_test.py
  library_generation/test/resources/test-config/config_without_gapics_key.yaml
  library_generation/test/resources/test-config/config_without_gapics_value.yaml
  library_generation/test/resources/test-config/config_without_library_value.yaml
  library_generation/test/resources/test-config/generation_config_with_duplicate_library_name.yaml
  library_generation/test/utilities_unit_tests.py
  library_generation/utils/utilities.py
Labels: size: l

#2696 chore: add a log in config checker
  library_generation/cli/entry_point.py
Labels: size: xs

#2697 fix: Log HttpJson's async thread pool core size
  gax-java/gax/src/main/java/com/google/api/gax/core/InstantiatingExecutorProvider.java
Labels: size: xs

#2698 chore: run library generation jobs conditionally
  .github/workflows/verify_library_generation.yaml
Labels: size: s
