Repository googleapis/sdk-platform-java, pull requests merged in 2024-05, with the labels that each got.

#2615 chore: bake synthtool and owl-bot into library_generation docker image
  .cloudbuild/library_generation/library_generation.Dockerfile
  library_generation/DEVELOPMENT.md
  library_generation/README.md
  library_generation/generate_composed_library.py
  library_generation/model/generation_config.py
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/postprocess_library.sh
  library_generation/test/generate_pr_description_unit_tests.py
  library_generation/test/generate_repo_unit_tests.py
  library_generation/test/integration_tests.py
  library_generation/test/model/config_change_unit_tests.py
  library_generation/test/model/generation_config_unit_test.py
  library_generation/test/resources/integration/google-cloud-java/baseline_generation_config.yaml
  library_generation/test/resources/integration/google-cloud-java/current_generation_config.yaml
  library_generation/test/resources/integration/java-bigtable/generation_config.yaml
  library_generation/test/resources/test-config/config_without_owlbot.yaml
  library_generation/test/resources/test-config/config_without_synthtool.yaml
  library_generation/test/resources/test-config/config_without_temp_excludes.yaml
  library_generation/test/resources/test-config/generation_config.yaml
  library_generation/test/utilities_unit_tests.py
  library_generation/test/utils/generation_config_comparator_unit_tests.py
Labels: size: l

#2711 chore: update java version to 17 in dependency analyzer
  .github/workflows/analyze_dependency.yaml
Labels: size: xs

#2712 chore: skip library generation tests after merging a pull request
  .github/workflows/verify_library_generation.yaml
Labels: size: xs

#2713 chore: remove test output
  library_generation/test/integration_tests.py
Labels: size: xs

#2716 chore: fix verify_library_generation.yaml for forks
  .github/workflows/verify_library_generation.yaml
Labels: size: xs

#2718 chore: do not run workflow on push
  .github/workflows/verify_library_generation.yaml
Labels: size: s

#2715 fix: Return resolved endpoint from StubSettings' Builder
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallContext.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonCallContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/testing/FakeCallContext.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITEndpointContext.java
Labels: size: m

#2721 chore: follow up fix to verify_library_generation
  .github/workflows/verify_library_generation.yaml
Labels: size: s

#2731 fix: only append `.api.grpc` suffix to group id if the artifact id starts with `proto-` or `grpc-`
  library_generation/README.md
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/owlbot/src/fix_poms.py
  library_generation/setup.py
  library_generation/test/compare_poms.py
  library_generation/test/owlbot/__init__.py
  library_generation/test/owlbot/fix_poms_unit_tests.py
  library_generation/test/resources/test-owlbot/java-admanager/.repo-metadata.json
  library_generation/test/resources/test-owlbot/java-admanager/ad-manager-bom/pom-golden.xml
  library_generation/test/resources/test-owlbot/java-admanager/ad-manager/pom-golden.xml
  library_generation/test/resources/test-owlbot/java-admanager/pom-golden.xml
  library_generation/test/resources/test-owlbot/java-admanager/proto-ad-manager-v1/pom-golden.xml
  library_generation/test/resources/test-owlbot/java-admanager/versions.txt
Labels: size: l

#2739 ci: add timestamps to graalvm's mvn setup commands
  .cloudbuild/graalvm/cloudbuild-test-a.yaml
  .cloudbuild/graalvm/cloudbuild-test-b.yaml
  .cloudbuild/graalvm/cloudbuild.yaml
  .kokoro/presubmit/downstream-build.sh
Labels: size: m

#2740 fix: do not populate repo level change while removing library
  library_generation/test/utils/generation_config_comparator_unit_tests.py
  library_generation/utils/generation_config_comparator.py
Labels: size: s

#2738 test: destroy httpJsonComplianceClient after tests.
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITDynamicRoutingHeaders.java
Labels: size: xs

#2748 chore: Await Termination for clients in Dynamic Routing Headers Showcase Test
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITDynamicRoutingHeaders.java
Labels: size: s

#2677 chore: remove unused CLIs
  library_generation/cli/generate_monorepo_gapic_bom.py
  library_generation/generate_pr_description.py
  library_generation/generate_repo.py
Labels: size: m

#2760 ci: increase graalvm ci machine type
  .cloudbuild/graalvm/cloudbuild-test-a-downstream-kms.yaml
  .cloudbuild/graalvm/cloudbuild-test-a-downstream-kmsinventory.yaml
  .cloudbuild/graalvm/cloudbuild-test-a.yaml
  .cloudbuild/graalvm/cloudbuild-test-b-downstream-kms.yaml
  .cloudbuild/graalvm/cloudbuild-test-b-downstream-kmsinventory.yaml
  .cloudbuild/graalvm/cloudbuild-test-b.yaml
Labels: size: s

#2736 fix: opentelemetry-bom to be in third-party-dependencies BOM
  gapic-generator-java-bom/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: s

#2737 test: add showcase test for api-version
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ApiClientHeaderProvider.java
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITApiVersionHeaders.java
Labels: size: l

#2761 fix: prepare to generate grafeas
  library_generation/test/resources/test_mv_src/gapic/destination/java_gapic_srcjar/src/main/java/example_main.txt
  library_generation/test/resources/test_mv_src/gapic/destination/java_gapic_srcjar/src/test/java/example_test.txt
  library_generation/test/resources/test_mv_src/proto/destination/java_gapic_srcjar/proto/src/main/java/example_proto_main.txt
  library_generation/test/resources/test_mv_src/samples/destination_com/java_gapic_srcjar/samples/snippets/generated/src/main/java/com/example_com_sample.txt
  library_generation/test/resources/test_mv_src/samples/destination_io/java_gapic_srcjar/samples/snippets/generated/src/main/java/io/example_io_sample.txt
  library_generation/test/utilities_unit_tests.py
  library_generation/utils/utilities.sh
Labels: size: m

#2764 fix: Replace deprecated protobuf methods.
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
Labels: size: xs

#2774 chore: remove platformdirs
  library_generation/requirements.txt
Labels: size: xs

#2775 chore: exclude `prediction.proto`
  library_generation/generate_library.sh
Labels: size: xs

#2747 feat: add a github client
  java-shared-dependencies/dependency-analyzer/pom.xml
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/external/DepsDevClient.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/external/GitHubClient.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Interval.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/PullRequest.java
  java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/PullRequestStatistics.java
  java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/external/GitHubClientTest.java
  java-shared-dependencies/dependency-analyzer/src/test/resources/pull_request_sample_response.txt
Labels: size: l

#2781 chore: exclude `google-api-client-bom` from google api dependencies group
  renovate.json
Labels: size: xs

#2754 chore: use Junit5 in java core
  gapic-generator-java-pom-parent/pom.xml
  java-core/google-cloud-core-grpc/pom.xml
  java-core/google-cloud-core-grpc/src/test/java/com/google/cloud/grpc/BaseGrpcServiceExceptionTest.java
  java-core/google-cloud-core-grpc/src/test/java/com/google/cloud/grpc/GrpcTransportOptionsTest.java
  java-core/google-cloud-core-grpc/src/test/java/com/google/cloud/grpc/SharedResourceHolderTest.java
  java-core/google-cloud-core-http/pom.xml
  java-core/google-cloud-core-http/src/test/java/com/google/cloud/http/BaseHttpServiceExceptionTest.java
  java-core/google-cloud-core-http/src/test/java/com/google/cloud/http/CensusHttpModuleTest.java
  java-core/google-cloud-core-http/src/test/java/com/google/cloud/http/HttpTransportOptionsTest.java
  java-core/google-cloud-core/pom.xml
  java-core/google-cloud-core/src/test/java/com/google/cloud/AsyncPageImplTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/BaseSerializationTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/BaseServiceExceptionTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/BaseWriteChannelTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/BatchResultTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/ByteArrayTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/ConditionTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/DateTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/ExceptionHandlerTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/FieldSelectorHelperTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/IdentityTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/MonitoredResourceDescriptorTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/MonitoredResourceTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/PageImplTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/PolicyTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/PolicyV3Test.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/RetryOptionTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/RoleTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/ServiceOptionsTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/StringEnumTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/StructsTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/TimestampTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/testing/BaseEmulatorHelperTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/testing/CommandWrapperTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/testing/LogRecorderTest.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/testing/VersionTest.java
  java-core/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: l

#2720 feat: generate proto-only repository
  java-common-protos/codecov.yaml
  java-common-protos/owlbot.py
  java-iam/codecov.yaml
  library_generation/generate_repo.py
  library_generation/model/gapic_inputs.py
  library_generation/model/generation_config.py
  library_generation/test/cli/entry_point_unit_tests.py
  library_generation/test/model/gapic_inputs_unit_tests.py
  library_generation/test/model/generation_config_unit_tests.py
  library_generation/test/resources/goldens/.repo-metadata-proto-only-golden.json
  library_generation/test/resources/misc/BUILD_proto_only.bazel
  library_generation/test/utilities_unit_tests.py
  library_generation/utils/utilities.py
Labels: size: l

#2757 chore: Migrate Junit 4 to Junit 5 for showcase
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITApiVersionHeaders.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITAutoPopulatedFields.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITBidiStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITClientShutdown.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITClientSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITCommonServiceMixins.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITCrud.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITDynamicRoutingHeaders.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITEndpointContext.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITGdch.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITHttpAnnotation.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITIam.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITLongRunningOperation.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITNumericEnums.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITOtelMetrics.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITPagination.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryCallable.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryDeadline.java
  showcase/pom.xml
Labels: size: l

#2793 chore: remove resquests dependency from library_generation
  library_generation/requirements.txt
Labels: size: xs

#2772 chore: [hermetic-build] simplify usage of synthtool
  .cloudbuild/library_generation/library_generation.Dockerfile
  library_generation/cli/entry_point.py
  library_generation/generate_composed_library.py
  library_generation/generate_repo.py
  library_generation/model/generation_config.py
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/owlbot/src/apply_repo_templates.py
  library_generation/postprocess_library.sh
  library_generation/test/integration_tests.py
Labels: size: m, hermetic-build

#2707 chore: bake protoc into the hermetic build docker image
  .cloudbuild/library_generation/library_generation.Dockerfile
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/integration_tests.py
  library_generation/test/model/generation_config_unit_tests.py
  library_generation/test/utils/generation_config_comparator_unit_tests.py
  library_generation/utils/utilities.sh
  renovate.json
Labels: size: m

#2799 chore: add junit5 extension to setup environment variable
  .github/workflows/ci.yaml
  .github/workflows/sonar.yaml
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
  gax-java/gax/BUILD.bazel
  gax-java/gax/pom.xml
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
  gax-java/pom.xml
Labels: size: m

#2802 chore: tag graalvm images with infrastructure-public-image-
  .cloudbuild/graalvm/cloudbuild.yaml
Labels: size: xs

#2806 chore: do not create pr description without qualified commit
  library_generation/generate_pr_description.py
  library_generation/test/generate_pr_description_unit_tests.py
Labels: size: s

#2801 chore: remove `template_excludes` in the generation config
  generation_config.yaml
  library_generation/README.md
  library_generation/model/generation_config.py
  library_generation/test/generate_pr_description_unit_tests.py
  library_generation/test/generate_repo_unit_tests.py
  library_generation/test/model/config_change_unit_tests.py
  library_generation/test/model/generation_config_unit_tests.py
  library_generation/test/resources/integration/google-cloud-java/baseline_generation_config.yaml
  library_generation/test/resources/integration/google-cloud-java/current_generation_config.yaml
  library_generation/test/resources/integration/java-bigtable/generation_config.yaml
  library_generation/test/resources/test-config/generation_config.yaml
  library_generation/test/utilities_unit_tests.py
  library_generation/test/utils/generation_config_comparator_unit_tests.py
  library_generation/utils/utilities.py
Labels: size: m

#2823 chore: fix failing unit tests in `PathTemplateTest`
  api-common-java/src/test/java/com/google/api/pathtemplate/PathTemplateTest.java
Labels: size: s

#2824 chore: add library generation workflow
  .github/workflows/hermetic_library_generation.yaml
  .github/workflows/update_googleapis_commit.yaml
  library_generation/scripts/hermetic_library_generation.sh
  library_generation/scripts/update_googleapis_commit.sh
Labels: size: l

#2825 chore: add generation workflow
  .github/scripts/hermetic_library_generation.sh
  .github/scripts/update_googleapis_commit.sh
  .github/workflows/hermetic_library_generation.yaml
  .github/workflows/update_googleapis_commit.yaml
Labels: size: l

#2784 chore: remove Owlbot yaml
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: size: s

#2829 chore: change commit message
  library_generation/generate_pr_description.py
  library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt
  library_generation/test/utils/commit_message_formatter_unit_tests.py
  library_generation/utils/commit_message_formatter.py
Labels: size: m
