Repository googleapis/sdk-platform-java, pull requests merged in 2024-10, with the labels that each got.

#3251 chore: add a Cloud Build config to push library generation image to Artifact Registry
  .cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml
Labels: size: s

#3259 chore: update requirement.txt
  library_generation/requirements.in
  library_generation/requirements.txt
Labels: size: s

#3258 deps: update grpc dependencies to v1.67.1
  .cloudbuild/library_generation/library_generation.Dockerfile
  gapic-generator-java-pom-parent/pom.xml
Labels: size: xs

#3137 feat(gax): add API key authentication to ClientSettings
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientSettings.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientSettingsTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/testing/FakeStubSettings.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITApiKeyCredentials.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITApiVersionHeaders.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/GrpcCapturingClientInterceptor.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/HttpJsonCapturingClientInterceptor.java
Labels: size: l

#3257 fix: address incorrect universe domain validation when quota project id is set
  gax-java/gax/src/main/java/com/google/api/gax/rpc/internal/QuotaProjectIdHidingCredentials.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/internal/QuotaProjectIdHidingCredentialsTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITEndpointContext.java
Labels: size: s

#3272 fix: Disable automatically retrieving Universe Domain from Metadata Server
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
Labels: size: s

#3273 chore: update owlbot-cli committish
  .cloudbuild/library_generation/library_generation.Dockerfile
Labels: size: xs

#3186 feat(gax): append cred-type header for auth metrics
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
Labels: size: m

#3279 deps: update grpc dependencies to v1.67.1 in dependencies.properties
  gax-java/dependencies.properties
Labels: size: xs

#3289 chore: remove release-please in generated README.md
  library_generation/owlbot/templates/java_library/README.md
  library_generation/test/owlbot/java_unit_tests.py
  library_generation/test/resources/test-owlbot/fixtures/java_templates/render-readme/.repo-metadata.json
  library_generation/test/resources/test-owlbot/testdata/README-golden.md
Labels: size: m

#3271 chore: bake Java formatter into image
  .cloudbuild/library_generation/library_generation.Dockerfile
  library_generation/DEVELOPMENT.md
  library_generation/README.md
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/owlbot/bin/format_source.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/utilities_unit_tests.py
  library_generation/utils/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: m

#3292 chore: bake Java formatter into image (#3271)
  .cloudbuild/library_generation/library_generation.Dockerfile
  library_generation/DEVELOPMENT.md
  library_generation/README.md
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/owlbot/bin/format_source.sh
  library_generation/test/generate_library_unit_tests.sh
  library_generation/test/utilities_unit_tests.py
  library_generation/utils/utilities.sh
  showcase/scripts/generate_showcase.sh
Labels: size: m

#3199 feat(gax): add protobuf version tracking to headers
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/GaxHttpJsonProperties.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/GaxHttpJsonPropertiesTest.java
  gax-java/gax/src/main/java/com/google/api/gax/core/GaxProperties.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ApiClientHeaderProvider.java
  gax-java/gax/src/test/java/com/google/api/gax/core/GaxPropertiesTest.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ApiClientHeaderProviderTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITVersionHeaders.java
Labels: size: m

#3293 fix: generator setting incorrect name/class for sample due to region tag (2nd attempt)
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposer.java
  test/integration/goldens/apigeeconnect/samples/snippets/generated/main/java/com/google/cloud/apigeeconnect/v1/connectionservice/create/SyncCreateUseHttpJsonTransport.java
  test/integration/goldens/asset/samples/snippets/generated/main/java/com/google/cloud/asset/v1/assetservice/create/SyncCreateUseHttpJsonTransport.java
  test/integration/goldens/credentials/samples/snippets/generated/main/java/com/google/cloud/iam/credentials/v1/iamcredentials/create/SyncCreateUseHttpJsonTransport.java
  test/integration/goldens/library/samples/snippets/generated/main/java/com/google/cloud/example/library/v1/libraryservice/create/SyncCreateUseHttpJsonTransport.java
  test/integration/goldens/redis/samples/snippets/generated/main/java/com/google/cloud/redis/v1beta1/cloudredis/create/SyncCreateUseHttpJsonTransport.java
Labels: samples, size: m

#3290 feat: selectively generate libraries
  library_generation/cli/entry_point.py
  library_generation/generate_repo.py
  library_generation/test/cli/entry_point_unit_tests.py
  library_generation/test/generate_repo_unit_tests.py
  library_generation/test/resources/test-config/monorepo_baseline.yaml
  library_generation/test/resources/test-config/monorepo_current.yaml
Labels: size: l

#3296 chore: suppress pull progress
  .github/scripts/hermetic_library_generation.sh
  library_generation/test/integration_tests.py
Labels: size: xs

#3301 chore: update base image to latest
  .cloudbuild/library_generation/library_generation.Dockerfile
Labels: size: xs

#3315 fix: add additional potential exceptions when retrieving protobuf manifest file to get version
  gax-java/gax/src/main/java/com/google/api/gax/core/GaxProperties.java
Labels: size: xs

#3316 deps: update dependency com.google.errorprone:error_prone_annotations to v2.35.1
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#3320 chore: skip formatting test-jdk17 files in firestore
  hermetic_build/library_generation/owlbot/bin/format_source.sh
Labels: size: xs

#3321 feat: Update Gapic-Generator to generate libraries using `java.time` methods
  .gitignore
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/RetrySettingsComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/samplecode/SettingsSampleComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/common/RetrySettingsComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingServiceV2StubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/PublisherStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/servicesettings/SyncWait.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/servicesettings/stub/SyncWait.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/SettingsSampleComposerTest.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/MessagingSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/EchoStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/IdentityStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/MessagingStubSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/SequenceServiceStubSettings.java
  showcase/gapic-showcase/src/main/resources/META-INF/native-image/com.google.showcase.v1beta1/reflect-config.json
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/ConnectionServiceStubSettings.java
  test/integration/goldens/asset/samples/snippets/generated/main/java/com/google/cloud/asset/v1/assetservicesettings/exportassets/SyncExportAssets.java
  test/integration/goldens/asset/samples/snippets/generated/main/java/com/google/cloud/asset/v1/stub/assetservicestubsettings/exportassets/SyncExportAssets.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/AssetServiceSettings.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  test/integration/goldens/bigtable/src/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java
  test/integration/goldens/compute/samples/snippets/generated/main/java/com/google/cloud/compute/v1small/addressessettings/delete/SyncDelete.java
  test/integration/goldens/compute/samples/snippets/generated/main/java/com/google/cloud/compute/v1small/stub/addressesstubsettings/delete/SyncDelete.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/AddressesSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/AddressesStubSettings.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/RegionOperationsStubSettings.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java
  test/integration/goldens/iam/src/com/google/iam/v1/stub/IAMPolicyStubSettings.java
  test/integration/goldens/kms/src/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/stub/LibraryServiceStubSettings.java
  test/integration/goldens/logging/samples/snippets/generated/main/java/com/google/cloud/logging/v2/configsettings/copylogentries/SyncCopyLogEntries.java
  test/integration/goldens/logging/samples/snippets/generated/main/java/com/google/cloud/logging/v2/stub/configservicev2stubsettings/copylogentries/SyncCopyLogEntries.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/ConfigSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java
  test/integration/goldens/logging/src/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java
  test/integration/goldens/pubsub/src/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java
  test/integration/goldens/redis/samples/snippets/generated/main/java/com/google/cloud/redis/v1beta1/cloudredissettings/createinstance/SyncCreateInstance.java
  test/integration/goldens/redis/samples/snippets/generated/main/java/com/google/cloud/redis/v1beta1/stub/cloudredisstubsettings/createinstance/SyncCreateInstance.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/CloudRedisSettings.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  test/integration/goldens/storage/src/com/google/storage/v2/stub/StorageStubSettings.java
Labels: size: l

#3324 chore(hermetic-build): use secure base image hosted in docker.com
  .cloudbuild/library_generation/library_generation.Dockerfile
  hermetic_build/library_generation/generate_library.sh
  hermetic_build/library_generation/owlbot/bin/entrypoint.sh
  hermetic_build/library_generation/tests/generate_library_unit_tests.py
  hermetic_build/library_generation/tests/generate_library_unit_tests.sh
Labels: size: m

#3328 chore: remove .m2 folder mapping in library generation workflow
  .github/scripts/hermetic_library_generation.sh
Labels: size: xs
