Repository googleapis/sdk-platform-java, pull requests merged in 2024-02, with the labels that each got.

#2437 test: increase timeout testCancelOuterFutureAfterStart to 60s
  gax-java/gax/src/test/java/com/google/api/gax/retrying/ScheduledRetryingExecutorTest.java
Labels: size: xs

#2444 test: fix flaky HttpJsonDirectServerStreamingCallableTest.testOnResponseError
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
Labels: size: m

#2431 feat: add `generate_repo.py`
  .github/workflows/verify_library_generation.yaml
  .gitignore
  library_generation/__init__.py
  library_generation/generate_composed_library.py
  library_generation/generate_repo.py
  library_generation/main.py
  library_generation/model/GapicConfig.py
  library_generation/model/GenerationConfig.py
  library_generation/model/Library.py
  library_generation/model/LibraryConfig.py
  library_generation/model/bom_config.py
  library_generation/model/gapic_config.py
  library_generation/model/gapic_inputs.py
  library_generation/model/generation_config.py
  library_generation/model/library_config.py
  library_generation/model/repo_config.py
  library_generation/new_client/get_generator_version_from_workspace.sh
  library_generation/new_client/new-client.py
  library_generation/new_client/requirements.in
  library_generation/new_client/requirements.txt
  library_generation/new_client/templates.py
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/postprocess_library.sh
  library_generation/repo-level-postprocess/generate_gapic_bom.sh
  library_generation/repo-level-postprocess/generate_root_pom.sh
  library_generation/templates/gapic-libraries-bom.xml.j2
  library_generation/templates/owlbot.py.j2
  library_generation/templates/owlbot.yaml.monorepo.j2
  library_generation/templates/root-pom.xml.j2
  library_generation/test/compare_poms.py
  library_generation/test/generate_library_integration_test.sh
  library_generation/test/integration_tests.py
  library_generation/test/resources/goldens/.OwlBot-golden.yaml
  library_generation/test/resources/goldens/.repo-metadata-golden.json
  library_generation/test/resources/goldens/owlbot-golden.py
  library_generation/test/resources/integration/google-cloud-java/generation_config.yaml
  library_generation/test/resources/integration/java-bigtable/generation_config.yaml
  library_generation/test/resources/misc/BUILD_service_config_relative_target.bazel
  library_generation/test/resources/misc/BUILD_service_yaml_absolute_target.bazel
  library_generation/test/resources/misc/versions.txt
  library_generation/test/resources/test_repo_level_postprocess/gapic-libraries-bom/pom-golden.xml
  library_generation/test/resources/test_repo_level_postprocess/java-dns/pom.xml
  library_generation/test/resources/test_repo_level_postprocess/java-service-control/google-cloud-service-control-bom/pom.xml
  library_generation/test/resources/test_repo_level_postprocess/java-tasks/google-cloud-tasks-bom/pom.xml
  library_generation/test/resources/test_repo_level_postprocess/pom-golden.xml
  library_generation/test/resources/test_repo_level_postprocess/versions.txt
  library_generation/test/unit_tests.py
  library_generation/utilities.py
  library_generation/utilities.sh
Labels: size: xl

#2447 chore: add `setup.py` for `library_generation`
  .gitignore
  library_generation/.gitignore
  library_generation/setup.py
  library_generation/test/integration_tests.py
Labels: size: s

#2452 chore: format python code
  library_generation/setup.py
  library_generation/test/integration_tests.py
Labels: size: s

#2449 chore: update instructions on `generate_repo.py`
  library_generation/README.md
Labels: size: l

#2451 chore: update dev guide to get version of gapic-showcase to install.
  showcase/README.md
Labels: size: xs

#2446 chore: refactor golden tests for autopopulation feature
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoClientTest.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/GrpcAutoPopulateFieldStub.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/GrpcEchoStub.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncChat.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncChatAgain.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncCollect.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncCollideName.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncEcho.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/AsyncExpand.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/SyncCollideName.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoclient/SyncEcho.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonAutoPopulateFieldTestingStub.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonEchoStub.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientCallableMethodSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientMethodSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ServiceYamlParserTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/TestProtoLoader.java
  gapic-generator-java/src/test/proto/auto_populate_field_testing.proto
  gapic-generator-java/src/test/proto/echo.proto
  gapic-generator-java/src/test/resources/auto_populate_field_testing.yaml
  gapic-generator-java/src/test/resources/echo_v1beta1.yaml
Labels: automerge, size: xl

#2455 fix: Apiary Host returns user set host if set
  java-core/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
  java-core/google-cloud-core/src/test/java/com/google/cloud/ServiceOptionsTest.java
Labels: size: s

#2464 chore: remove unused files from showcase.
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/BlurbName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/ProfileName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/RoomName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/SequenceName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/SequenceReportName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/SessionName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/StreamingSequenceName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/StreamingSequenceReportName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/TestName.java
  showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/UserName.java
Labels: size: xl

#2471 chore: move owlbot requirements to library_generation/reqs.in
  library_generation/owlbot/src/requirements.in
  library_generation/owlbot/src/requirements.txt
  library_generation/postprocess_library.sh
  library_generation/requirements.in
Labels: size: l

#2456 chore: add opentelemery to shared dependencies
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: s

#2360 fix: Cancel the Timeout Task for HttpJson
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCallImpl.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonClientCallImplTest.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITClientShutdown.java
Labels: size: l

#2457 chore: add library params
  library_generation/model/generation_config.py
  library_generation/model/library_config.py
  library_generation/test/resources/test-config/generation_config.yaml
  library_generation/test/unit_tests.py
  library_generation/utilities.py
Labels: size: s

#2487 chore: fix workflow to create additional tags
  .github/workflows/create_additional_release_tag.yaml
Labels: size: xs

#2358 chore: remove beta httpjson
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceSettingsClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonAutoPopulateFieldTestingStub.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonRoutingHeadersStub.golden
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/ComplianceSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/IdentitySettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/MessagingSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/SequenceServiceSettings.java
  showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/TestingSettings.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/ConnectionServiceSettings.java
  test/integration/goldens/apigeeconnect/src/com/google/cloud/apigeeconnect/v1/stub/HttpJsonConnectionServiceStub.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/AssetServiceSettings.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/stub/HttpJsonAssetServiceStub.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/HttpJsonAddressesStub.java
  test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/HttpJsonRegionOperationsStub.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/IamCredentialsSettings.java
  test/integration/goldens/credentials/src/com/google/cloud/iam/credentials/v1/stub/HttpJsonIamCredentialsStub.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/LibraryServiceSettings.java
  test/integration/goldens/library/src/com/google/cloud/example/library/v1/stub/HttpJsonLibraryServiceStub.java
  test/integration/goldens/redis/src/com/google/cloud/redis/v1beta1/CloudRedisSettings.java
Labels: size: m

#2045 docs: Add contribution guidelines.
  CONTRIBUTING.md
Labels: size: xs

#2450 fix: cleanup @BetaApi from Resource Name Builder Methods
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposer.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/resourcename/goldens/AgentName.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/resourcename/goldens/FoobarName.golden
  showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/BlurbName.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/FeedName.java
  test/integration/goldens/asset/src/com/google/cloud/asset/v1/SavedQueryName.java
  test/integration/goldens/logging/src/com/google/logging/v2/CmekSettingsName.java
  test/integration/goldens/logging/src/com/google/logging/v2/LogBucketName.java
  test/integration/goldens/logging/src/com/google/logging/v2/LogExclusionName.java
  test/integration/goldens/logging/src/com/google/logging/v2/LogName.java
  test/integration/goldens/logging/src/com/google/logging/v2/LogSinkName.java
  test/integration/goldens/logging/src/com/google/logging/v2/LogViewName.java
  test/integration/goldens/logging/src/com/google/logging/v2/SettingsName.java
  test/integration/goldens/pubsub/src/com/google/pubsub/v1/TopicName.java
Labels: size: m

#2496 chore: suppress download progress
  library_generation/owlbot/bin/entrypoint.sh
Labels: size: xs

#2468 fix: Fix watchdog to start with WAITING state
  gax-java/gax/src/main/java/com/google/api/gax/rpc/Watchdog.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/WatchdogTest.java
Labels: size: m

#2493 chore: add docker image for hermetic build scripts
  .cloudbuild/cloudbuild-library-generation.yaml
  .cloudbuild/cloudbuild-test-library-generation.yaml
  .cloudbuild/library_generation.Dockerfile
  library_generation/dockerignore
  library_generation/generate_repo.py
  library_generation/postprocess_library.sh
  library_generation/setup.py
  library_generation/test/container_integration_tests.sh
  library_generation/test/integration_tests.py
Labels: size: m

#2504 deps: adding the dependencies for java-pubsublite and java-bigquery
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: s

#2510 chore: create release cloudbuild yaml for library_generation
  .cloudbuild/google-cloud-sdk.repo
  .cloudbuild/graalvm/cloudbuild-test-a.yaml
  .cloudbuild/graalvm/cloudbuild-test-b.yaml
  .cloudbuild/graalvm/cloudbuild.yaml
  .cloudbuild/graalvm/graalvm_a.Dockerfile
  .cloudbuild/graalvm/graalvm_b.Dockerfile
  .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
  .cloudbuild/library_generation/cloudbuild-library-generation-release.yaml
  .cloudbuild/library_generation/cloudbuild-test-library-generation.yaml
  .cloudbuild/library_generation/library_generation.Dockerfile
Labels: size: m

#2519 test: do not show unnecessary BatcherImplTest logging
  gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: automerge, size: s

#2454 fix: remove @BetaApi from ApiFutures and ApiService
  api-common-java/src/main/java/com/google/api/core/ApiFutures.java
  api-common-java/src/main/java/com/google/api/core/ApiService.java
Labels: size: xs

#2521 build(deps): update dependency com.google.cloud:google-cloud-shared-config to v1.7.4
  .cloudbuild/graalvm/cloudbuild-test-a.yaml
  .cloudbuild/graalvm/cloudbuild-test-b.yaml
  .cloudbuild/graalvm/cloudbuild.yaml
  gapic-generator-java-pom-parent/pom.xml
  gax-java/gax-bom/pom.xml
  java-shared-dependencies/first-party-dependencies/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
  java-shared-dependencies/upper-bound-check/pom.xml
  sdk-platform-java-config/pom.xml
  showcase/pom.xml
Labels: size: s

#2509 feat: improve batching summary errors
  gax-java/gax/src/main/java/com/google/api/gax/batching/BatcherStats.java
  gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherStatsTest.java
Labels: size: m

#2524 fix: adjust release please config to reflect file location change.
  .cloudbuild/graalvm/cloudbuild-test-a.yaml
  .cloudbuild/graalvm/cloudbuild-test-b.yaml
  .cloudbuild/graalvm/cloudbuild.yaml
  .cloudbuild/library_generation/cloudbuild-library-generation-release.yaml
  .github/release-please.yml
  release-please-config.json
Labels: size: s
