Repository googleapis/sdk-platform-java, pull requests merged in 2024-03, with the labels that each got.

#2505 chore: re-enable HW processing for hermetic build scripts
  .gitignore
  library_generation/generate_composed_library.py
  library_generation/generate_repo.py
  library_generation/model/generation_config.py
  library_generation/model/library_config.py
  library_generation/owlbot/bin/entrypoint.sh
  library_generation/owlbot/src/fix-poms.py
  library_generation/postprocess_library.sh
  library_generation/test/container_integration_tests.sh
  library_generation/test/integration_tests.py
  library_generation/test/resources/goldens/.repo-metadata-monorepo-golden.json
  library_generation/test/resources/goldens/.repo-metadata-non-monorepo-golden.json
  library_generation/test/resources/integration/google-cloud-java/generation_config.yaml
  library_generation/test/resources/integration/java-bigtable/generation_config.yaml
  library_generation/test/resources/test_monorepo_postprocessing/gapic-libraries-bom/pom-golden.xml
  library_generation/test/resources/test_monorepo_postprocessing/java-dns/pom.xml
  library_generation/test/resources/test_monorepo_postprocessing/java-service-control/google-cloud-service-control-bom/pom.xml
  library_generation/test/resources/test_monorepo_postprocessing/java-tasks/google-cloud-tasks-bom/pom.xml
  library_generation/test/resources/test_monorepo_postprocessing/pom-golden.xml
  library_generation/test/resources/test_monorepo_postprocessing/versions.txt
  library_generation/test/unit_tests.py
  library_generation/utilities.py
Labels: size: l

#2485 feat: Universe Domain Environment Variable Support
  .github/workflows/ci.yaml
  .github/workflows/sonar.yaml
  gapic-generator-java-pom-parent/pom.xml
  gax-java/gax/pom.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
Labels: size: m

#2539 chore: add `jq` to hermetic build image definition
  .cloudbuild/library_generation/library_generation.Dockerfile
Labels: size: xs, hermetic-build

#2541 chore: fix renovate bot configs for java-shared-config updates
  renovate.json
Labels: size: xs

#2531 feat: get PR description from googleapis commits
  .github/workflows/verify_library_generation.yaml
  library_generation/generate_pr_description.py
  library_generation/test/integration_tests.py
  library_generation/test/resources/integration/google-cloud-java/generation_config.yaml
  library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt
  library_generation/test/resources/integration/java-bigtable/pr-description-golden.txt
  library_generation/test/unit_tests.py
  library_generation/test/utils/__init__.py
  library_generation/test/utils/commit_message_formatter_unit_tests.py
  library_generation/utilities.py
  library_generation/utils/commit_message_formatter.py
Labels: size: l

#2548 chore: write description to a file
  library_generation/generate_pr_description.py
  library_generation/test/integration_tests.py
Labels: size: xs

#2542 chore: recursive comparison in hermetic build IT
  library_generation/test/integration_tests.py
  library_generation/test/resources/integration/google-cloud-java/generation_config.yaml
  library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt
  library_generation/test/resources/integration/java-bigtable/generation_config.yaml
Labels: size: m

#2553 feat: Add shopping and chat common protos.
  java-common-protos/.OwlBot.yaml
Labels: automerge, size: s

#2555 feat: skip build only commit
  library_generation/generate_pr_description.py
  library_generation/test/resources/integration/google-cloud-java/generation_config.yaml
  library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt
Labels: size: s

#2554 chore: remove `google/shopping/type/types.proto` when generating shopping APIs
  library_generation/generate_library.sh
Labels: size: xs

#2556 chore: remove generator in PR description
  library_generation/generate_pr_description.py
  library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt
  library_generation/test/resources/integration/java-bigtable/pr-description-golden.txt
Labels: size: s

#2563 chore: remove unused `library_generation/configuration` folder
  library_generation/configuration/owlbot-cli-sha
  library_generation/configuration/python-version
  library_generation/configuration/synthtool-commitish
Labels: size: xs

#2557 chore: refactor utility functions
  library_generation/cli/generate_monorepo_gapic_bom.py
  library_generation/cli/generate_monorepo_root_pom.py
  library_generation/generate_repo.py
  library_generation/test/test_utils.py
  library_generation/test/utilities_unit_tests.py
  library_generation/test/utils/monorepo_postprocessor_unit_tests.py
  library_generation/test/utils/pom_generator_unit_tests.py
  library_generation/utilities.py
  library_generation/utils/file_render.py
  library_generation/utils/monorepo_postprocessor.py
  library_generation/utils/pom_generator.py
Labels: size: l

#2568 chore: modify pr description
  library_generation/generate_pr_description.py
  library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt
  library_generation/test/resources/integration/java-bigtable/pr-description-golden.txt
  library_generation/test/utils/commit_message_formatter_unit_tests.py
  library_generation/utils/commit_message_formatter.py
Labels: size: s

#2500 feat: Introduce OpenTelemetry Metrics Recording
  gapic-generator-java-bom/pom.xml
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
  gax-java/gax/BUILD.bazel
  gax-java/gax/pom.xml
  gax-java/gax/src/main/java/com/google/api/gax/tracing/MetricsTracer.java
  gax-java/gax/src/main/java/com/google/api/gax/tracing/OpenTelemetryMetricsRecorder.java
  gax-java/gax/src/test/java/com/google/api/gax/tracing/MetricsTracerTest.java
  gax-java/gax/src/test/java/com/google/api/gax/tracing/OpenTelemetryMetricsRecorderTest.java
  gax-java/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITOtelMetrics.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/TestClientInitializer.java
  showcase/pom.xml
Labels: automerge, size: xl

#2574 deps: normalize dependencies
  api-common-java/pom.xml
  gapic-generator-java-pom-parent/pom.xml
  gapic-generator-java/pom.xml
  java-core/pom.xml
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: s

#2559 fix(deps): add detector-resource-support dependencies
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: automerge, size: xs

#2580 fix: Update shopping and chat common protos.
  java-common-protos/.OwlBot.yaml
Labels: automerge, size: xs

#2593 feat: Add JavadocJar Task to build.gradle for self service libraries
  rules_java_gapic/resources/gradle/client_grpc.gradle.tmpl
  rules_java_gapic/resources/gradle/client_grpcrest.gradle.tmpl
  rules_java_gapic/resources/gradle/client_rest.gradle.tmpl
Labels: size: s

#2572 fix: correct deep-remove and deep-preserve regexes
  library_generation/postprocess_library.sh
Labels: kokoro:run, size: s

#2587 feat: add generation config comparator
  library_generation/model/library_config.py
  library_generation/test/integration_tests.py
  library_generation/test/model/__init__.py
  library_generation/test/model/library_config_unit_tests.py
  library_generation/test/utilities_unit_tests.py
  library_generation/test/utils/generation_config_comparator_unit_tests.py
  library_generation/utilities.py
  library_generation/utils/generation_config_comparator.py
Labels: size: l

#2595 chore: remove ending comma in `owlbot.py`
  library_generation/templates/owlbot.py.j2
  library_generation/test/resources/goldens/owlbot-golden.py
Labels: size: xs

#2601 chore: sync renovate template from synthtool
  library_generation/owlbot/templates/java_library/renovate.json
Labels: size: s

#2598 feat: generate selected libraries
  library_generation/generate_repo.py
  library_generation/test/generate_repo_unit_tests.py
  library_generation/utilities.py
Labels: size: m

#2607 fix: add main to `generate_repo.py`
  library_generation/generate_repo.py
Labels: size: xs

#2611 chore: update renovate to explicitly ignore workflow files
  library_generation/owlbot/templates/java_library/renovate.json
Labels: size: xs
