Repository googleapis/sdk-platform-java, pull requests merged in 2025-04, with the labels that each got.

#3712 chore: allow --api-path as option to generate cmd and generate per api/majorversion
  hermetic_build/common/cli/get_changed_libraries.py
  hermetic_build/common/model/generation_config.py
  hermetic_build/common/model/library_config.py
  hermetic_build/common/tests/model/generation_config_unit_tests.py
  hermetic_build/common/tests/utils/proto_path_utils_unit_tests.py
  hermetic_build/common/utils/proto_path_utils.py
  hermetic_build/library_generation/cli/entry_point.py
  hermetic_build/library_generation/generate_repo.py
  hermetic_build/library_generation/tests/cli/entry_point_unit_tests.py
  hermetic_build/library_generation/tests/cli/versions.txt
  hermetic_build/library_generation/tests/generate_repo_unit_tests.py
  hermetic_build/release_note_generation/cli/generate_release_note.py
Labels: size: l

#3734 chore: prepare showcase for GraalVM for JDK 17
  java-showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITHttpAnnotation.java
Labels: size: xs

#3732 chore(sec): prefix hermetic-build images with `infrastructure-public-image`
  .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
Labels: size: xs

#3737 chore: introduce .kokoro templates for GraalVM jobs
  .github/workflows/verify_library_generation.yaml
  hermetic_build/library_generation/owlbot/templates/java_library/.github/sync-repo-settings.yaml
  hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/renovate_config_check.yaml
  hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/update_generation_config.yaml
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/build.sh
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-a.cfg
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-b.cfg
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-c.cfg
  hermetic_build/library_generation/setup.py
Labels: automerge, size: l

#3743 fix(hermetic-build): use correct image name in templated graalvm jobs
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-a.cfg
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-c.cfg
Labels: size: xs

#3730 feat: Selective gapic generation phase II
  gapic-generator-java/src/main/java/com/google/api/generator/engine/ast/JavaDocComment.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/comment/CommentComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/comment/ServiceClientCommentComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/comment/SettingsCommentComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientTestClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceSettingsClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractTransportServiceStubClassComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposer.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/utils/CommonStrings.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/Method.java
  gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
  gapic-generator-java/src/test/java/com/google/api/generator/engine/ast/JavaDocCommentTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceClientClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubSettingsClassComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoServiceSelectiveGapicClient.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoServiceSelectiveGapicClientStub.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoServiceSelectiveGapicServiceSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoServiceSelectiveGapicStubSettings.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/AsyncChatAgainShouldGenerateAsPublic.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/AsyncChatAgainShouldGenerateAsUsual.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/AsyncChatShouldGenerateAsInternal.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/AsyncChatShouldGenerateAsPublic.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/AsyncChatShouldGenerateAsUsual.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/AsyncEchoShouldGenerateAsInternal.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/AsyncEchoShouldGenerateAsPublic.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/AsyncEchoShouldGenerateAsUsual.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncChatShouldGenerateAsInternal.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncChatShouldGenerateAsInternalFoobarname.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncChatShouldGenerateAsInternalNoargs.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncChatShouldGenerateAsInternalString.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncCreateSetCredentialsProvider.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncCreateSetEndpoint.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncEchoShouldGenerateAsPublic.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncEchoShouldGenerateAsPublicFoobarname.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncEchoShouldGenerateAsPublicNoargs.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncEchoShouldGenerateAsPublicString.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncEchoShouldGenerateAsUsual.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncEchoShouldGenerateAsUsualFoobarname.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncEchoShouldGenerateAsUsualNoargs.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/echoserviceselectivegapicclient/SyncEchoShouldGenerateAsUsualString.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/servicesettings/SyncEchoShouldGenerateAsUsual.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/servicesettings/stub/SyncEchoShouldGenerateAsUsual.golden
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposerTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java
  gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/TestProtoLoader.java
  gapic-generator-java/src/test/proto/selective_api_generation.proto
  gapic-generator-java/src/test/resources/selective_api_generation_generate_omitted_v1beta1.yaml
  gapic-generator-java/src/test/resources/selective_api_generation_v1beta1.yaml
Labels: size: xl

#3749 chore: update generation config
  .github/scripts/hermetic_library_generation.sh
  generation_config.yaml
  hermetic_build/common/cli/get_changed_libraries.py
  hermetic_build/common/model/config_change.py
  java-common-protos/proto-google-common-protos/src/main/java/com/google/rpc/ErrorDetailsProto.java
  java-common-protos/proto-google-common-protos/src/main/java/com/google/rpc/QuotaFailure.java
  java-common-protos/proto-google-common-protos/src/main/proto/google/rpc/error_details.proto
Labels: size: xl

#3753 build: fix nightly failures in Java 11 jobs
  .github/workflows/nightly.yaml
Labels: size: xs

#3752 fix: use spotify formatter in hermetic build templates
  hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/ci.yaml
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/build.sh
Labels: size: s

#3754 fix: use java 17 in samples.yaml
  hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/samples.yaml
Labels: samples, size: xs

#3759 fix: keep native image templates up to date
  .github/release-please.yml
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-a.cfg
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-b.cfg
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-c.cfg
Labels: size: xs

#3762 fix: inline version update in kokoro templates
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-a.cfg
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-b.cfg
  hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-c.cfg
  release-please-config.json
Labels: size: s

#3765 fix: subscribe Airlock Docker image definition to GRPC updates
  renovate.json
Labels: size: xs
