Repository googleapis/sdk-platform-java, pull requests merged in 2025-07, with the labels that each got.

#3860 chore: create LTS branch 2.59.x
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: m

#3863 deps: update arrow.version to 17.0.0, auth deps to 1.37.1 and http-client deps to 1.47.1
  gax-java/dependencies.properties
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: s

#3764 fix: make generation config update logs verbose
  hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh
Labels: size: xs

#3873 fix: improve error messaging for LRO CancellationException
  gax-java/gax/src/main/java/com/google/api/gax/longrunning/OperationTimedPollAlgorithm.java
Labels: size: xs
