Repository googleapis/sdk-platform-java, pull requests merged in 2025-02, with the labels that each got.

#3402 deps: Update OpenTelemetry semantic convention packages in the shared dependencies
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#3591 feat: Enable MTLS_S2A bound token by default for gRPC S2A enabled flows
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: size: m

#3592 chore: Fix testCancelGetAttempt flaky test
  gax-java/gax/src/test/java/com/google/api/gax/retrying/AbstractRetryingExecutorTest.java
  gax-java/gax/src/test/java/com/google/api/gax/retrying/ScheduledRetryingExecutorTest.java
Labels: size: m

#3613 ci: scoping the permission in create_additional_release_tag.yaml
  .github/workflows/create_additional_release_tag.yaml
Labels: size: xs

#3572 feat: enable DirectPath bound token in InstantiatingGrpcChannelProvider
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: size: m

#3617 chore: adjust native-image config for spring-cloud-gcp
  gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
Labels: size: xs

#3622 fix: Avoid creating message string prematurely for streaming calls
  gax-java/gax/src/main/java/com/google/api/gax/rpc/StateCheckingResponseObserver.java
Labels: size: xs

#3628 chore: Update DEVELOPMENT.md according to WORKSPACE
  gapic-generator-java/DEVELOPMENT.md
Labels: size: xs

#3635 deps: Update opentelemetry-semconv to v1.29.0-alpha
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#3634 test: remove wildcard in test class import
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcTransportChannelTest.java
Labels: size: xs

#3403 feat: add client side logging with slf4j
  .github/workflows/ci.yaml
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
  gax-java/gax-grpc/pom.xml
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcLoggingInterceptor.java
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcLoggingInterceptorTest.java
  gax-java/gax-httpjson/pom.xml
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonLoggingInterceptor.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/InstantiatingHttpJsonChannelProvider.java
  gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ManagedHttpJsonChannel.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonLoggingInterceptorTest.java
  gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/InstantiatingHttpJsonChannelProviderTest.java
  gax-java/gax/BUILD.bazel
  gax-java/gax/pom.xml
  gax-java/gax/src/main/java/com/google/api/gax/logging/LogData.java
  gax-java/gax/src/main/java/com/google/api/gax/logging/LoggerProvider.java
  gax-java/gax/src/main/java/com/google/api/gax/logging/LoggingUtils.java
  gax-java/gax/src/main/java/com/google/api/gax/logging/Slf4jLoggingHelpers.java
  gax-java/gax/src/main/java/com/google/api/gax/logging/Slf4jUtils.java
  gax-java/gax/src/test/java/com/google/api/gax/logging/LogDataTest.java
  gax-java/gax/src/test/java/com/google/api/gax/logging/LoggerProviderTest.java
  gax-java/gax/src/test/java/com/google/api/gax/logging/LoggingEnabledTest.java
  gax-java/gax/src/test/java/com/google/api/gax/logging/LoggingUtilsTest.java
  gax-java/gax/src/test/java/com/google/api/gax/logging/Slf4jUtilsTest.java
  gax-java/gax/src/test/java/com/google/api/gax/logging/TestLogger.java
  gax-java/gax/src/test/java/com/google/api/gax/logging/TestMDCAdapter.java
  gax-java/gax/src/test/java/com/google/api/gax/logging/TestServiceProvider.java
  gax-java/gax/src/test/resources/META-INF/services/org.slf4j.spi.SLF4JServiceProvider
  gax-java/pom.xml
  showcase/gapic-showcase/pom.xml
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/logging/ITLogging.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/logging/ITLogging1x.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/logging/ITLoggingDisabled.java
  showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/logging/TestAppender.java
  showcase/pom.xml
Labels: size: xl

#3651 fix: S2A gRPC flow creates ComputeEngineCredentials via newBuilder.
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
Labels: size: s

#3659 docs: update showcase readme
  showcase/README.md
Labels: size: xs

#3658 deps: update grpc to 1.70.0 (missed update)
  .cloudbuild/library_generation/library_generation.Dockerfile
  gapic-generator-java-pom-parent/pom.xml
  java-common-protos/grpc-google-common-protos/src/main/java/com/google/cloud/location/LocationsGrpc.java
  java-common-protos/grpc-google-common-protos/src/main/java/com/google/longrunning/OperationsGrpc.java
  java-iam/grpc-google-iam-v1/src/main/java/com/google/iam/v1/IAMPolicyGrpc.java
  java-iam/grpc-google-iam-v2/src/main/java/com/google/iam/v2/PoliciesGrpc.java
  java-iam/grpc-google-iam-v2beta/src/main/java/com/google/iam/v2beta/PoliciesGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/ComplianceGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/IdentityGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/MessagingGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/SequenceServiceGrpc.java
  showcase/grpc-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/TestingGrpc.java
Labels: size: xl

#3657 deps: update google http client dependencies to v1.46.3
  gapic-generator-java-pom-parent/pom.xml
  gax-java/dependencies.properties
Labels: size: xs

#3662 chore: update googleapis commit
  generation_config.yaml
Labels: size: xs

#3668 feat: next release from main branch is 2.55.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: m
