Repository googleapis/sdk-platform-java, pull requests merged in 2025-01, with the labels that each got.

#3565 ci: remove unnecessary distributionManagement section
  java-common-protos/pom.xml
  java-iam/pom.xml
Labels: size: s

#3567 chore: temporarily disable updating grpc and guava versions until after LTS is released
  renovate.json
Labels: size: xs

#3091 chore: setup declarative configuration for branch protection and release-please
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: m

#3571 chore: add jdk 23 job for showcase tests
  .github/workflows/ci.yaml
Labels: size: s

#3467 feat: add support for new setAllowHardBoundTokens field.
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: size: s

#3548 feat: revert #3400: reintroduce experimental S2A integration in client libraries grpc transport
  gax-java/gax-grpc/clirr-ignored-differences.xml
  gax-java/gax-grpc/pom.xml
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcLongRunningTest.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
  gax-java/gax-grpc/src/test/resources/README.md
  gax-java/gax-grpc/src/test/resources/client_cert.pem
  gax-java/gax-grpc/src/test/resources/client_key.pem
  gax-java/gax-grpc/src/test/resources/root_cert.pem
  gax-java/gax-httpjson/clirr-ignored-differences.xml
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/TransportChannelProvider.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
Labels: size: l

#3574 chore: prepare showcase for Graal SDK 23.x
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/nativeimage/GrpcNettyFeature.java
Labels: size: xs

#2706 feat: migrate away from deprecated graal-sdk dependency to use nativeimage
  gax-java/dependencies.properties
  gax-java/gax-grpc/pom.xml
  gax-java/gax/pom.xml
Labels: size: xs
