Repository googleapis/sdk-platform-java, pull requests merged in 2025-05, with the labels that each got.

#3768 deps: Update maven-shared-utils to v3.2.1
  java-shared-dependencies/dependency-convergence-check/pom.xml
  java-shared-dependencies/unmanaged-dependency-check/pom.xml
Labels: size: s

#3767 fix: Only send mtlsEndpoint if it is non-null
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
Labels: size: m

#3735 chore: add jdk 8 verification to showcase CI
  .github/workflows/ci.yaml
Labels: size: m

#3777 fix: Update IAM v3 groupId to the correct value
  java-iam/grpc-google-iam-v3/pom.xml
  java-iam/pom.xml
  java-iam/proto-google-iam-v3/pom.xml
Labels: size: s

#3786 feat: add cloudbuild config to publish image via AR Exit Gate
  .cloudbuild/library_generation/cloudbuild-library-generation-push-exitgate.yaml
Labels: size: s

#3800 fix: manage graalvm image versions via Hermetic Build templates _only_
  hermetic_build/library_generation/owlbot/templates/java_library/renovate.json
Labels: size: s

#3796 chore: remove print from java-showcase owlbot.py
  java-showcase/owlbot.py
Labels: size: xs

#3816 chore: temporarily stop using maven mirror
  .kokoro/presubmit/downstream-build.sh
  settings.xml
Labels: size: s

#3817 feat: use debian base image for `java-library-generation`
  .cloudbuild/library_generation/library_generation.Dockerfile
  .cloudbuild/library_generation/library_generation_airlock.Dockerfile
Labels: size: m
