Repository googleapis/sdk-platform-java, pull requests merged in 2025-03, with the labels that each got.

#3675 deps: update arrow.version to v18.2.0
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#3670 fix: remove call credentials from call options if DirectPath
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallContext.java
  gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcCallContextTest.java
Labels: size: m

#3685 chore: fix showcase clirr test after java-showcase renaming
  .github/workflows/ci.yaml
Labels: size: xs

#3686 chore: fix logback-classic version for testing
  java-showcase/gapic-showcase/pom.xml
Labels: size: xs

#3688 chore: add java 8 compatibility check
  .github/workflows/java_compatibility_check.yaml
Labels: size: s

#3689 chore: add aliases to generate command options.
  hermetic_build/library_generation/cli/entry_point.py
Labels: size: xs

#3690 build(deps): update dependency com.google.cloud:google-cloud-shared-config to v1.15.0
  .cloudbuild/graalvm/cloudbuild-test-a-downstream-kms.yaml
  .cloudbuild/graalvm/cloudbuild-test-a-downstream-kmsinventory.yaml
  .cloudbuild/graalvm/cloudbuild-test-a.yaml
  .cloudbuild/graalvm/cloudbuild-test-b-downstream-kms.yaml
  .cloudbuild/graalvm/cloudbuild-test-b-downstream-kmsinventory.yaml
  .cloudbuild/graalvm/cloudbuild-test-b.yaml
  .cloudbuild/graalvm/cloudbuild.yaml
  gapic-generator-java-pom-parent/pom.xml
  gax-java/gax-bom/pom.xml
  java-shared-dependencies/first-party-dependencies/pom.xml
  java-shared-dependencies/upper-bound-check/pom.xml
  java-showcase/pom.xml
  sdk-platform-java-config/pom.xml
Labels: size: s

#3694 deps: revert "deps: update arrow.version to v18.2.0"
  java-shared-dependencies/third-party-dependencies/pom.xml
Labels: size: xs

#3650 ci: Use Linkage Checker to test Binary Compatibility
  .github/workflows/downstream_protobuf_compatibility_check_nightly.yaml
  .kokoro/nightly/common.sh
  .kokoro/nightly/downstream-protobuf-binary-compatibility.sh
  .kokoro/nightly/downstream-protobuf-source-compatibility.sh
Labels: size: m

#3699 ci: Update protobuf compatibility ci to default to 4.29.0
  .github/workflows/downstream_protobuf_compatibility_check_nightly.yaml
Labels: size: xs

#3683 ci: Speed up Protobuf Compatibility checks by running specific modules in Google-Cloud-Java
  .kokoro/nightly/common.sh
  .kokoro/nightly/downstream-protobuf-binary-compatibility.sh
  .kokoro/nightly/downstream-protobuf-source-compatibility.sh
Labels: size: s

#3674 chore: centralize graal 23 downstream updates
  gax-java/gax/src/test/resources/META-INF/native-image/com.google.api/gax/native-image.properties
Labels: size: xs

#3700 chore: allow generation-input as folder that supplies config and vers…
  hermetic_build/library_generation/cli/entry_point.py
  hermetic_build/library_generation/generate_repo.py
  hermetic_build/library_generation/tests/cli/entry_point_unit_tests.py
  hermetic_build/library_generation/utils/utilities.py
Labels: size: m

#3706 chore: create logging module structure
  .github/workflows/java_sdk_logging.yaml
  gapic-generator-java-pom-parent/pom.xml
  gax-java/pom.xml
  java-sdk-logging/java.header
  java-sdk-logging/license-checks.xml
  java-sdk-logging/log4j2-extension/pom.xml
  java-sdk-logging/logback-extension/pom.xml
  java-sdk-logging/pom.xml
Labels: size: m

#3709 chore: update logging mod
  .github/workflows/java_sdk_logging.yaml
  java-sdk-logging/license-checks.xml
  java-sdk-logging/log4j2-extension/pom.xml
  java-sdk-logging/logback-extension/pom.xml
  java-sdk-logging/pom.xml
Labels: size: s

#3713 chore: update workflow template
  hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh
Labels: size: s

#3673 fix: plumb mtls endpoint to TransportChannelProvider
  gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-java/gax/clirr-ignored-differences.xml
  gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java
  gax-java/gax/src/main/java/com/google/api/gax/rpc/TransportChannelProvider.java
  gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
Labels: size: m

#3711 chore(hermetic-build): infer formatter version from java-shared-config property
  .cloudbuild/library_generation/library_generation.Dockerfile
Labels: size: s

#3710 chore: include java-storage-nio changes in GraalVM config
  gax-java/gax/pom.xml
  gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
  gax-java/gax/src/test/resources/META-INF/native-image/com.google.api/gax/native-image.properties
Labels: size: xs

#3716 ci: Use Java 8 for Linkage Checker
  .github/workflows/downstream_protobuf_compatibility_check_nightly.yaml
  .kokoro/nightly/downstream-protobuf-binary-compatibility.sh
  .kokoro/nightly/downstream-protobuf-source-compatibility.sh
Labels: size: s

#3721 chore: add httpcore5 and httpclient5 to third-party-dependencies
  java-shared-dependencies/third-party-dependencies/pom.xml
  java-shared-dependencies/upper-bound-check/pom.xml
Labels: do not merge, size: s

#3727 chore: remove logging module
  .github/workflows/java_sdk_logging.yaml
  java-sdk-logging/java.header
  java-sdk-logging/license-checks.xml
  java-sdk-logging/log4j2-extension/pom.xml
  java-sdk-logging/logback-extension/pom.xml
  java-sdk-logging/pom.xml
Labels: size: m
